---
title: "UNEP-Gap-Report-Standard-Figures"
author: "William F. Lamb"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)

rm(list = ls())

library(tidyverse)
library(openxlsx)
library(countrycode)
library(ggrepel)
library(patchwork)
library(WDI)
library(grid)
library(zoo)

source("https://raw.githubusercontent.com/lambwf/Codebase/main/figure_style.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/growth_rate.R")

load("data/data_edgar.RData")
load("data/data_gcb_luc.RData")
load("data/data_gcb_co2_ffi.RData")

high_emitters <- c("China","United States","India","European Union","Russia","Brazil","World")


cc_EU <- read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/european-union.csv") %>% 
  select(iso=Code) %>% 
  mutate(EU="1")

cc_LDC <- read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/refs/heads/main/data/ldc.csv") %>% 
  select(iso=Code) %>% 
  mutate(LDC=1)


## Get population data from the World Bank

data_wdi_pop <- WDI(country = "all",indicator = "SP.POP.TOTL",start = 1970,end = 2023,extra=TRUE,language = "en") %>%
  select(iso3c, country, year, SP.POP.TOTL) %>%
  filter(!is.na(iso3c))

data_wdi_pop$population <- data_wdi_pop$SP.POP.TOTL
data_wdi_pop$iso <- data_wdi_pop$iso3c
data_wdi_pop<-data_wdi_pop %>% select(-SP.POP.TOTL,-iso3c)


```

## Global totals
### Trend by gas

``` {r total_trend, fig.height = 4, fig.width = 8}

## Aggregate emissions data

data_total <- data_edgar %>% 
  group_by(year,gas) %>% 
  summarise(value=sum(value,na.rm=T)/1e9)

data_total_luc <- data_gcb_luc %>% 
  filter(country=="Global") %>% 
  mutate(value=value/1e9)


# Add the GCB projection for 2023 (https://essd.copernicus.org/articles/15/5301/2023/) and join

data_total_luc <- data_total_luc %>% 
  add_row(year=2023,value=1.1*(44/12))

data_total_luc <- data_total_luc %>% 
  mutate(gas="CO2 LULUCF") %>% 
  select(-iso,-country)

data_total <- rbind(data_total,data_total_luc) %>% 
  filter(year>=1990)


## Arrange levels

data_total <- data_total %>% 
  mutate(gas = as.factor(gas)) %>% 
  mutate(gas = fct_relevel(gas,"F-gases","N2O","CH4","CO2 LULUCF","CO2 Fossil"))


## Calculate the rate of change in the past year

data_total_change <- data_total %>% 
  rbind(.,data_total %>% 
          group_by(year) %>% 
          summarise(value=sum(value)) %>% 
          mutate(gas="Total"))

# Arrange new levels

data_total_change <- data_total_change %>% 
  mutate(gas = as.factor(gas)) %>% 
  mutate(gas = fct_relevel(gas,"Total","F-gases","N2O","CH4","CO2 LULUCF","CO2 Fossil"))

# Calculate growth rates

data_total_change <- data_total_change %>% 
  filter(year >= max(data_total$year)-1) %>% 
  group_by(gas) %>% 
  mutate(change=growth_rate(year,value)$rate) %>% 
  mutate(change=change*100) %>% 
  mutate(change=signif(change,2)) %>% 
  mutate(change=ifelse(change>0,paste0("+",change,"%"),paste0("-",abs(change),"%"))) %>% 
  filter(year==max(data_total$year)) %>%
  ungroup()


## Calculate the position of each label

data_total_change <- data_total_change %>% 
  left_join(.,data_total_change %>% 
              filter(gas!="Total") %>% 
              arrange(desc(gas)) %>% 
              mutate(label_position=value) %>%
              mutate(label_position=cumsum(label_position)) %>% 
              mutate(label_position=label_position-(value/2)) %>% 
              select(gas,label_position)) %>% 
  mutate(label_position=ifelse(gas=="Total",value,label_position))

data_total_change <- data_total_change %>% 
  mutate(value=round(value,1)) %>% 
  mutate(label=paste0(gas,": ",value," ",change,""))


## Plot

p1 <- data_total %>% ggplot(.,aes(x=year,y=value,fill=gas)) +
  geom_col(color="#252525",linewidth=0.25, width=1) +
  theme_wl_bar_trend() +
  scale_fill_manual(values=colours_gases) +
  scale_y_continuous(breaks=c(0,20,40,60),limits=c(0,70)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2020,max(data_total$year)),
                     expand = expansion(mult = c(0.05, 0.01))) +
  theme(axis.title = element_blank(),
        legend.position = "none") +
  labs(title="Total net greenhouse gas emissions",
       subtitle=bquote(paste("GtCO"[2], "e/year")),
       caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGAR v9, GCB 2023  \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on bookkeeping conventions")


p2 <- data_total_change %>% 
  ggplot(.,aes(x=1,y=ifelse(gas!="CO2 Fossil",label_position-6,label_position),label=label,color=gas)) +
  geom_text_repel(
    hjust=0,
    direction = "y",
    point.size = NA,
    size=3.5,
    show.legend = FALSE,
    min.segment.length = Inf,
    box.padding = 0.2,
    force = 0.1) +
  annotation_custom(grob = textGrob("Emissions in 2023,\n1 year change:",
                                    x = unit(0.03, "npc"), y = unit(0.88, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.9)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=colours_gases) +
  scale_y_continuous(limits = c(0,70)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
  theme_wl_empty()

plot <- p1 + p2 + plot_layout(widths=c(5,1.55))
plot



ggsave(plot,filename = "UNEP-EGR-2024-total-gas-trend.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-total-gas-trend.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-total-gas-trend.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_total %>% mutate(units="GtCO2e/year (GWP100 AR6)"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-total-gas-trend.xlsx"),overwrite=T)



```

### Uncertainties

```{r uncertainties, fig.height = 4, fig.width = 7}

## Aggregate emissions data

data_uncertainties <- data_edgar %>%
  group_by(year,gas) %>% 
  summarise(value=sum(value,na.rm=T)/1e9)

data_uncertainties_luc <- data_gcb_luc %>% 
  filter(country=="Global") %>% 
  mutate(value=value/1e9)

# Add the GCB projection for 2023 (https://essd.copernicus.org/articles/15/5301/2023/) and join

data_uncertainties_luc <- data_uncertainties_luc %>% 
  add_row(year=2023,value=1.1*(44/12))

data_uncertainties_luc <- data_uncertainties_luc %>% 
  mutate(gas="CO2 LULUCF") %>% 
  select(-iso,-country)

data_uncertainties <- rbind(data_uncertainties,data_uncertainties_luc) %>% 
  filter(year==max(data_uncertainties$year))


## Calculate uncertainties

data_uncertainties <- data_uncertainties %>% 
  left_join(.,data.frame(gas=c("CO2 Fossil","CO2 LULUCF","CH4","N2O","F-gases"),
                         uncertainty=c(0.08,0.7,0.3,0.6,0.3)),by=join_by(gas)) %>%
  mutate(uncertainty_abs=value*uncertainty)


## Aggregate total uncertainty

data_uncertainties_total <- data_uncertainties %>% 
  mutate(uncertainty_abs=uncertainty_abs^2) %>% 
  group_by(year) %>% 
  summarise(value=sum(value,na.rm=TRUE),
            uncertainty_abs=sqrt(sum(uncertainty_abs,na.rm=TRUE))) %>% 
  mutate(gas="Total")


data_uncertainties <- data_uncertainties %>% 
  bind_rows(.,data_uncertainties_total)


## Generate labels

data_uncertainties <- data_uncertainties %>% 
  mutate(label=ifelse(gas %in% c("CO2 Fossil","Total"),
                      paste0(signif(value,3)," ± ",signif(uncertainty_abs,2)),
                      paste0(signif(value,2)," ± ",signif(uncertainty_abs,2))))


## Arrange levels

data_uncertainties$gas <- as.factor(data_uncertainties$gas)
data_uncertainties$gas <- fct_relevel(data_uncertainties$gas,
                                      "F-gases","N2O","CH4","CO2 LULUCF",
                                      "CO2 Fossil","Total")

## Plot

plot <- data_uncertainties %>% ggplot(.,aes(x=value,y=gas,fill=gas,label=label)) +
  geom_col(color="#252525",linewidth=0.25) +
  geom_errorbarh(aes(xmin=value-uncertainty_abs,xmax=value+uncertainty_abs),
                 height=0.4,colour="#525252") +
  geom_text(aes(x=value+uncertainty_abs+1),hjust=0,colour="#636363") +
  theme_wl() +
  scale_fill_manual(values=colours_gases) +
  scale_x_continuous(breaks=c(0,10,20,30,40,50,60),expand = expansion(mult = c(0.05, 0.15))) +
  theme(legend.position = "none",
        axis.title = element_blank(),
        panel.grid.major.y = element_blank(),
        plot.title = element_text(margin=margin(t=15))) +
  labs(title="Total net greenhouse gas emissions and their uncertainties",
       subtitle=bquote(paste("GtCO"[2], "e in 2023")),
       caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGAR v9, GCB 2023  \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on bookkeeping conventions")
plot 

ggsave(plot,filename = "UNEP-EGR-2024-total-uncertainties.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-total-uncertainties.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-total-uncertainties.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_uncertainties %>% mutate(units="GtCO2e/year (GWP100 AR6)"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-total-uncertainties.xlsx"),overwrite=T)



```

### Trend by sector

``` {r total_trend, fig.height = 4, fig.width = 8}

## Aggregate emissions data

data_sectors <- data_edgar %>% 
  group_by(year,sector_lv2,sector_lv2_order) %>% 
  summarise(value=sum(value,na.rm=T)/1e9)

data_sectors_luc <- data_gcb_luc %>% 
  filter(country=="Global") %>% 
  mutate(value=value/1e9)


# Add the GCB projection for 2023 (https://essd.copernicus.org/articles/15/5301/2023/) and join

data_sectors_luc <- data_sectors_luc %>% 
  add_row(year=2023,value=1.1*(44/12))

data_sectors_luc <- data_sectors_luc %>%
  mutate(sector_lv2="Land use change (LULUCF)") %>% 
  mutate(sector_lv2_order=8) %>% 
  select(-iso,-country)

data_sectors <- rbind(data_sectors,data_sectors_luc) %>% 
  filter(year>=1990)


## Arrange levels

data_sectors$sector_lv2 <- as.factor(data_sectors$sector_lv2)
data_sectors$sector_lv2 <- fct_reorder(data_sectors$sector_lv2,data_sectors$sector_lv2_order)


data_sectors <- data_sectors %>% 
  arrange(year,sector_lv2)

## Calculate the rate of change in the past year

data_sectors_change <- data_sectors %>%
  rbind(.,data_sectors %>%
          group_by(year) %>%
          summarise(value=sum(value)) %>%
          mutate(sector_lv2="Total")) %>% 
  mutate(sector_lv2_order=ifelse(is.na(sector_lv2_order),1,sector_lv2_order+1))


# Arrange new levels

data_sectors_change$sector_lv2 <- as.factor(data_sectors_change$sector_lv2)
data_sectors_change$sector_lv2 <- fct_reorder(data_sectors_change$sector_lv2,data_sectors_change$sector_lv2_order)


# Calculate growth rates

data_sectors_change <- data_sectors %>% 
  filter(year >= max(data_sectors$year)-1) %>% 
  group_by(sector_lv2) %>% 
  mutate(change=growth_rate(year,value)$rate) %>% 
  mutate(change=change*100) %>% 
  mutate(change=signif(change,2)) %>% 
  mutate(change=ifelse(change>0,paste0("+",change,"%"),paste0("-",abs(change),"%"))) %>% 
  filter(year==max(data_sectors$year)) %>%
  ungroup()


## Calculate the position of each label

data_sectors_change <- data_sectors_change %>% 
  left_join(.,data_sectors_change %>% 
              filter(sector_lv2!="Total") %>% 
              arrange(desc(sector_lv2)) %>% 
              mutate(label_position=value) %>%
              mutate(label_position=cumsum(label_position)) %>% 
              mutate(label_position=label_position-(value/2)) %>% 
              select(sector_lv2,label_position)) %>% 
  mutate(label_position=ifelse(sector_lv2=="Total",value,label_position))

data_sectors_change <- data_sectors_change %>% 
  mutate(value=round(value,1)) %>% 
  mutate(label=paste0(sector_lv2,": ",value," ",change,""))

data_sectors_change <- data_sectors_change %>% 
  arrange(sector_lv2) %>% 
  mutate(label_position = seq(55, 0, length.out = nrow(data_sectors_change)))

## Plot

p1 <- data_sectors %>% ggplot(.,aes(x=year,y=value,fill=sector_lv2)) +
  geom_col(color="#252525",linewidth=0.25,width=1) +
  theme_wl_bar_trend() +
  scale_fill_manual(values=colours_9_sectors) +
  scale_y_continuous(breaks=c(0,20,40,60),limits=c(0,70)) +
  scale_x_continuous(breaks=c(1990,2000,2010,2020,max(data_sectors$year)),
                     expand = expansion(mult = c(0.05, 0.01))) +
  theme(axis.title = element_blank(),
        legend.position = "none") +
  labs(title="Total net greenhouse gas emissions by sector",
       subtitle=bquote(paste("GtCO"[2], "e/year")),
       caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGAR v9, GCB 2023  \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on bookkeeping conventions")


p2 <- data_sectors_change %>% 
  ggplot(.,aes(x=1,y=label_position,label=label,color=sector_lv2)) +
  geom_text(size=3.5,hjust=0) +
  annotation_custom(grob = textGrob("Emissions in 2023,\n1 year change:",
                                    x = unit(0, "npc"), y = unit(0.88, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.9)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=colours_9_sectors) +
  scale_y_continuous(limits = c(0,70)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
  theme_wl_empty() +
  theme(legend.position="none")

plot <- p1 + p2 + plot_layout(widths=c(5,3))
plot


ggsave(plot,filename = "UNEP-EGR-2024-total-sector-trend.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-total-sector-trend.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-total-sector-trend.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_sectors %>% select(-sector_lv2_order) %>% mutate(units="GtCO2e/year (GWP100 AR6)"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-total-sector-trend.xlsx"),overwrite=T)

```

### Land use change differences

```{r luc_differences, fig.height=4, fig.width=8}

## Load GCB land use change CO2 data (bookkeeping models)

source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_gcb_countries_v2023.R")

data_luc_diff <- load_gcb_countries_luc(
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=2),
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=3),
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=4)) %>% 
  filter(country=="Global") %>% 
  rename(BLUE=blue,`H&N`=hn,OSCAR=oscar,`Bookkeeping average`=mean) %>% 
  select(-country,-iso)


## Join Grassi NGHGI land use change CO2 data (inventories)

data_luc_inv <- read.xlsx('sources/not public/LULUCF NGHGI data for UNEP 2024.xlsx',startRow = 3) %>% 
  rename(category=LAND.CATEGORY,country=UNFCCC.country,iso=country.code)
data_luc_inv <- gather(data_luc_inv,year,Inventories,`2000`:`2023`) %>% 
  filter(category=="LULUCF net") %>% 
  filter(country=="World") %>% 
  mutate(Inventories=Inventories/1000) %>% 
  select(year,Inventories)

data_luc_diff <- data_luc_diff %>% 
  left_join(.,data_luc_inv,by=join_by(year)) %>% 
  gather(.,var,value,-units,-year) %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(year>=1990) %>% 
  select(year,var,value,units) %>% 
  mutate(units="GtCO2/year")


## Join FAO land use change CO2 data (inventory aligned, 3rd party)

data_fao <- read.csv("sources/FAO_Emissions_Totals_E_All_Data_NOFLAG.csv")
data_fao <- gather(data_fao,year,value,Y1961:Y2050)
data_fao$year <- gsub("Y","",data_fao$year)
data_fao <- data_fao %>% 
  select(country=Area,sector=Item,sector_code=Item.Code,gas=Element,units=Unit,source=Source,year,value)

data_fao <- data_fao %>% 
  filter(country=="World") %>% 
  filter(sector=="LULUCF") %>% 
  filter(gas=="Emissions (CO2)") %>% 
  filter(source=="FAO TIER 1") %>% 
  filter(year>=1990) %>% 
  filter(year!=2030) %>% 
  filter(year!=2050) %>% 
  mutate(year=as.numeric(year)) %>% 
  mutate(value=value/1e6) %>%
  mutate(var="FAO") %>% 
  mutate(units="GtCO2/year") %>% 
  select(year,var,value,units)

data_luc_diff <- data_luc_diff %>% 
  rbind(.,data_fao)


## Get minmax of the bookkeeping data

data_luc_minmax <- data_luc_diff %>% 
  filter(grepl("H&N",var) | grepl("BLUE",var) | grepl("OSCAR",var)) %>% 
  group_by(year) %>% 
  summarise(min=min(value),max=max(value))


## Create sequence in 5 year intervals for plotting dots

year_higlight <- seq(1990, max(data_luc_diff$year), by = 5)

if (!max(data_luc_diff$year) %in% year_higlight) {
  year_higlight <- c(year_higlight, max(data_luc_diff$year))
}


labels <- data_luc_diff %>% 
  filter(year>=max(data_luc_diff$year)-9) %>% 
  filter(var %in% c("Bookkeeping average","Inventories")) %>%
  group_by(var) %>% 
  summarise(value_end=last(value),value=mean(value)) %>% 
  mutate(year=paste0(max(data_luc_diff$year)-9,"-",max(data_luc_diff$year))) %>% 
  group_by(year) %>% 
  mutate(difference=first(value)-last(value))


data_luc_diff$var <- as.factor(data_luc_diff$var)
data_luc_diff$var <- fct_relevel(data_luc_diff$var,"Inventories","Bookkeeping average","BLUE","H&N","OSCAR","FAO")


p1 <- data_luc_diff %>% ggplot(.,aes(x=year,y=value,colour=var)) +
  geom_ribbon(data=data_luc_minmax,inherit.aes = FALSE,aes(x=year,ymin=min,ymax=max),fill="#74a6d4ff",alpha=0.25) +
  geom_path(size=1,fill="none") +
  geom_hline(yintercept=0,color="#636363",size = 0.25) +
  geom_point(data=data_luc_diff %>% 
               filter(year %in% year_higlight),
             shape=21,fill="white") +
  theme_wl() +
  scale_colour_manual(values=c("#7dd396ff","#3a5e91ff","#74a6d4ff","#74a6d4ff","#74a6d4ff","#4f8455ff")) +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.01))) +
  scale_y_continuous(breaks =c(-2,0,2,4,6,8)) +
  theme(axis.title = element_blank(),
        legend.position = "none") +
  labs(title="Differences in net land use change (LULUCF) estimates",
       subtitle=bquote(paste("GtCO"[2], "/year")),
       caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: GCB 2023, FAO 2024, Grassi et al. 2024  \n⌂ Note: bookkeeping and inventory estimates differ due to alternative system boundary definitions, see Grassi et al. 2023 ESSD")

p2 <- data_luc_diff %>% 
  filter(year==max(data_luc_diff$year)) %>% 
  mutate(value=ifelse(var=="OSCAR",value+0.4,value)) %>% 
  ggplot(.) +
  geom_segment(aes(x=3.9,xend=3.9,y=labels$value_end[1],yend=labels$value_end[2]),color="#636363",size = 0.25) +
  geom_segment(aes(x=3.75,xend=3.9,y=labels$value_end[1],yend=labels$value_end[1]),color="#636363",size = 0.25) +
  geom_segment(aes(x=3.75,xend=3.9,y=labels$value_end[2],yend=labels$value_end[2]),color="#636363",size = 0.25) +
  annotate("text",x=4,y=sum(labels$value_end),label=str_wrap(paste0("10 year avg. difference: ",signif(labels$difference,2), " Gt"),20),hjust=0,vjust=1,size=3.5,colour="#636363") +
  geom_text(aes(x=1,y=value,label=var,colour=var),hjust=0,size=3.5) +
  scale_colour_manual(values=c("#7dd396ff","#3a5e91ff","#74a6d4ff","#74a6d4ff","#74a6d4ff","#4f8455ff")) +
  scale_y_continuous(limits = layer_scales(p1)$y$range$range) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.01)),limits=c(1,6)) +
  theme_wl_empty() +
  theme(legend.position="none")


plot <- p1 + p2 + plot_layout(widths = c(5,2.9))
plot


ggsave(plot,filename = "UNEP-EGR-2024-total-luc-differences.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-total-luc-differences.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-total-luc-differences.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/); Grassi et al. 2024 (https://zenodo.org/records/7190601)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_luc_diff,colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-total-luc-differences.xlsx"),overwrite=T)

```

## Top 6 emitters
### Per capita emissions

```{r per_capita_emissions, fig.height=4, fig.width=9}

## Aggregate emissions data

data_percap <- data_edgar %>% 
  filter(year>=1990) %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=T))


## Join population and calculate per capita emissions, filter out NAs

data_percap <- data_percap %>% 
  left_join(.,data_wdi_pop %>% select(iso,year,population),by=join_by("iso","year")) %>% 
  mutate(ghg_pc=value/population) %>% 
  filter(!is.na(population))


## Add World

data_percap_world <- data_percap %>% 
  mutate(iso="WLD",country="World") %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value),population=sum(population)) %>% 
  mutate(ghg_pc=value/population)

data_percap <- rbind(data_percap,data_percap_world)


## Add Europe

data_percap_eu <- data_percap %>% 
  left_join(.,cc_EU,by="iso") %>% 
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27",country="European Union") %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value),population=sum(population)) %>% 
  mutate(ghg_pc=value/population)

data_percap <- rbind(data_percap,data_percap_eu)


## Calculate the rate of change in the past 3 years

data_percap_change <- data_percap %>% 
  filter(year >= max(data_percap$year)-3) %>% 
  group_by(iso) %>% 
  mutate(change=growth_rate(year,ghg_pc)$rate) %>% 
  mutate(change=change*100) %>% 
  mutate(change=signif(change,2)) %>% 
  mutate(change=ifelse(change>0,paste0("+",change,"%"),paste0("-",abs(change),"%"))) %>% 
  filter(year==max(data_percap$year))


## Create sequence in 5 year intervals for plotting dots

year_higlight <- seq(1990, max(data_percap$year), by = 5)

if (!max(data_percap$year) %in% year_higlight) {
  year_higlight <- c(year_higlight, max(data_percap$year))
}


## Plot

p1 <- data_percap %>% 
  filter(country %in% high_emitters) %>% 
  mutate(country=as.factor(country)) %>% 
  filter(year==max(data_percap$year)) %>% 
  ggplot(.,aes(x=ghg_pc,y=reorder(country,ghg_pc),fill=country,label=round(ghg_pc,1))) +
  
  geom_col(color='#252525',linewidth=0.25) +
  geom_text(aes(x = ghg_pc + 1,colour=country),hjust=0,size=3.5) + 
  annotation_custom(grob = textGrob("Year: 2023", x = unit(1, "npc"), y = unit(0, "npc"),hjust = 1, vjust = -0.3,
                                    gp = gpar(col = "#636363", fontsize = 10)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme_wl() +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.2))) +
  scale_fill_manual(values=colours_top6) +
  scale_colour_manual(values=colours_top6) +
  theme(legend.position="none",
        axis.title = element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="Per capita greenhouse gas emissions of the top six emitters",
       subtitle=bquote(paste("tCO"[2], "e/capita/year")),
       caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGAR v9, World Bank  \n⌂ Note: GWP100 AR6; land use change (LULUCF) emissions and removals excluded")

p2 <- data_percap %>% 
  filter(country %in% high_emitters) %>% 
  ggplot(.,aes(x=year,y=ghg_pc,colour=country)) +
  geom_path(size=1,fill="none") +
  
  geom_point(data=data_percap %>% 
               filter(country %in% high_emitters) %>% 
               filter(year %in% year_higlight),
             shape=21,fill="white") +
  scale_x_continuous(breaks = c(1990,2000,2010,2023)) +
  theme_wl() +
  scale_colour_manual(values=colours_top6) +
  theme(legend.position="none",
        axis.title = element_blank(),
        panel.grid.major.x = element_blank())

p3 <- data_percap_change %>% 
  filter(country %in% high_emitters) %>% 
  ggplot(.,aes(x=1,y=ghg_pc,label=change,color=country)) +
  geom_text_repel(
    hjust=0,
    direction = "y",
    point.size = NA,
    size=3.5,
    show.legend = FALSE,
    min.segment.length = Inf) +
  annotation_custom(grob = textGrob(str_wrap("3 year change:",10), x = unit(0.1, "npc"), y = unit(0.9, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.8)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=colours_top6) +
  scale_y_continuous(limits = layer_scales(p2)$y$range$range) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.01))) +
  theme_wl_empty()


plot <- p1 + p2 + plot_spacer() + p3 + plot_layout(widths=c(5,5,-0.35,1))
plot

ggsave(plot,filename = "UNEP-EGR-2024-top-percapita-exLUC.png",path = "results/standard/",device = "png",height = 4,width=9,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-top-percapita-exLUC.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=9)
ggsave(plot,filename = "UNEP-EGR-2024-top-percapita-exLUC.svg",path = "results/standard/",device = 'svg',height = 4,width=9)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); World Bank (https://databank.worldbank.org/source/population-estimates-and-projections)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_percap %>% select(iso,country,year,value=ghg_pc) %>% mutate(units="tCO2e/capita/year (GWP100 AR6)"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-top-percapita-exLUC.xlsx"),overwrite=T)

```

### Trends

```{r country_trend, fig.height=4, fig.width=9}


## Aggregate emissions data

data_trend <- data_edgar %>% 
  filter(year>=1990) %>% 
  group_by(iso,country,year) %>% 
  summarise(ghg=sum(value,na.rm=T)/1e6)


## Add Europe

data_trend_eu <- data_trend %>% 
  left_join(.,cc_EU,by="iso") %>% 
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27",country="European Union") %>% 
  group_by(iso,country,year) %>% 
  summarise(ghg=sum(ghg))

data_trend <- rbind(data_trend,data_trend_eu)


## Remove countries with 0 emissions

data_trend <- data_trend %>% 
  mutate(remove=ifelse(ghg==0,1,0)) %>% 
  group_by(iso) %>% 
  mutate(remove=sum(remove)) %>% 
  ungroup() %>% 
  filter(remove==0)


## Calculate the rate of change in the past 3 years

data_trend_change <- data_trend %>% 
  filter(year >= max(data_trend$year)-3) %>% 
  group_by(iso) %>% 
  mutate(change=growth_rate(year,ghg)$rate) %>% 
  mutate(change=change*100) %>% 
  mutate(change=signif(change,2)) %>% 
  mutate(change=ifelse(change>0,paste0("+",change,"%"),paste0("-",abs(change),"%"))) %>% 
  filter(year==max(data_trend$year))


## Create sequence in 5 year intervals for plotting dots

year_higlight <- seq(1990, max(data_trend$year), by = 5)

if (!max(data_trend$year) %in% year_higlight) {
  year_higlight <- c(year_higlight, max(data_trend$year))
}


p1 <- data_trend %>% 
  filter(country %in% high_emitters) %>% 
  mutate(country=as.factor(country)) %>% 
  filter(year==max(data_trend$year)) %>% 
  ggplot(.,aes(x=ghg,y=reorder(country,ghg),fill=country,label=signif(ghg,3))) +
  geom_col(color='#252525',linewidth=0.25) +
  geom_text(aes(x = ghg + 500,color=country),hjust=0,size=3.5) + 
  annotation_custom(grob = textGrob("Year: 2023", x = unit(1, "npc"), y = unit(0, "npc"),hjust = 1, vjust = -0.3,
                                    gp = gpar(col = "#636363", fontsize = 10)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme_wl() +
  scale_x_continuous(expand = expansion(mult = c(0.05, 0.2))) +
  scale_fill_manual(values=colours_top6) +
  scale_colour_manual(values=colours_top6) + 
  theme(legend.position="none",
        axis.title = element_blank(),
        panel.grid.major.y = element_blank()) +
  labs(title="Greenhouse gas emissions of the top six emitters",
       subtitle=bquote(paste("MtCO"[2], "e/year")),
       caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGAR v9, World Bank  \n⌂ Note: GWP100 AR6; land use change (LULUCF) emissions and removals excluded")

p2 <- data_trend %>% 
  filter(country %in% high_emitters) %>% 
  ggplot(.,aes(x=year,y=ghg,colour=country)) +
  geom_path(size=1) +
  
  geom_point(data=data_trend %>% 
               filter(country %in% high_emitters) %>% 
               filter(year %in% year_higlight),
             shape=21,fill="white") +
  scale_x_continuous(breaks = c(1990,2000,2010,2023)) +
  scale_y_continuous(limits = c(0,19000)) +
  theme_wl() +
  scale_colour_manual(values=colours_top6) +
  theme(legend.position="none",
        axis.title = element_blank(),
        panel.grid.major.x = element_blank())

p3 <- data_trend_change %>% 
  filter(country %in% high_emitters) %>% 
  ggplot(.,aes(x=1,y=ghg,label=change,color=country)) +
  geom_text_repel(
    hjust=0,
    direction = "y",
    point.size = NA,
    size=3.5,
    show.legend = FALSE,
    min.segment.length = Inf) +
  annotation_custom(grob = textGrob(str_wrap("3 year change:",10), x = unit(0.1, "npc"), y = unit(0.9, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.8)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=colours_top6) +
  scale_y_continuous(limits = c(0,19000)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.01))) +
  theme_wl_empty()


plot <- p1 + p2 + plot_spacer() + p3 + plot_layout(widths=c(5,5,-0.35,1))
plot


ggsave(plot,filename = "UNEP-EGR-2024-top-trend-exLUC.png",path = "results/standard/",device = "png",height = 4,width=9,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-top-trend-exLUC.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=9)
ggsave(plot,filename = "UNEP-EGR-2024-top-trend-exLUC.svg",path = "results/standard/",device = 'svg',height = 4,width=9)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_trend %>% select(iso,country,year,value=ghg) %>% mutate(units="MtCO2e/year (GWP100 AR6)"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-top-trend-exLUC.xlsx"),overwrite=T)

```

### Shares of annual total (top emitters)

``` {r top_emitter_shares, fig.height = 4, fig.width = 7}

## Aggregate emissions data

data_top_shares <- data_edgar %>% 
  filter(year>=1990) %>% 
  filter(year<=2022) %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## Join land use change (LULUCF) emissions from GCB

data_top_shares <- data_top_shares %>% 
  left_join(.,data_gcb_luc %>% select(iso,year,value_luc=value),
            by = join_by(iso, year)) %>% 
  rowwise() %>% 
  mutate(value = sum(value, value_luc, na.rm = TRUE)) %>%
  ungroup() %>% 
  select(-value_luc)

data_top_shares <- data_top_shares %>% 
  mutate(value=value/1e9)

## Join EU

data_top_shares_eu <- left_join(data_top_shares,cc_EU,by="iso") %>%
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27") %>% 
  select(-EU) %>%
  mutate(country="European Union") %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=T)) %>% 
  ungroup()

data_top_shares <- left_join(data_top_shares,cc_EU,by="iso") %>% 
  filter(is.na(EU)) %>% 
  bind_rows(.,data_top_shares_eu) %>% 
  select(-EU)


## Merge LDCs

data_top_shares_ldcs <- left_join(data_top_shares,cc_LDC,by="iso") %>%
  filter(!is.na(LDC)) %>% 
  mutate(iso="LDCS") %>% 
  select(-LDC) %>%
  mutate(country="Least Developed Countries") %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=T)) %>% 
  ungroup()

data_top_shares <- left_join(data_top_shares,cc_LDC,by="iso") %>% 
  filter(is.na(LDC)) %>% 
  bind_rows(.,data_top_shares_ldcs) %>% 
  select(-LDC)


## Get top x countries + LDCs

countries <- data_top_shares %>% 
  ungroup() %>% 
  filter(year==2022) %>% 
  filter(iso!="LDCS") %>% 
  arrange(desc(value)) %>% 
  head(6) %>% 
  mutate(rank=1) %>% 
  mutate(rank=cumsum(rank)) %>% 
  mutate(group=country) %>% 
  select(iso,group,rank) %>% 
  add_row(iso="LDCS",group="Least Developed Countries",rank=8)


## Group rest of world

data_top_shares <- left_join(data_top_shares,countries,by="iso") %>% 
  mutate(group=ifelse(is.na(group),"Rest of world",group)) %>% 
  mutate(rank=ifelse(group=="Rest of world",7,rank))

data_top_shares <- data_top_shares %>% 
  group_by(group,rank,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## Arrange factor levels

data_top_shares$group <- as.factor(data_top_shares$group)
data_top_shares$group <- fct_reorder(data_top_shares$group,data_top_shares$rank)
data_top_shares <- data_top_shares %>% arrange(group)


## Calculate shares

data_top_shares <- data_top_shares %>% 
  left_join(.,data_top_shares %>% 
              group_by(year) %>% 
              summarise(total=sum(value,na.rm=T)),by="year") %>% 
  mutate(share=100*(value/total))


## Calculate label positions

labels <- data_top_shares %>% 
  filter(year==2022) %>% 
  ungroup() %>% 
  arrange(desc(group)) %>% 
  mutate(label_position=share) %>%
  mutate(label_position=cumsum(label_position)) %>% 
  mutate(label_position=label_position-(share/2)) %>% 
  mutate(label=paste0(group," ",round(share),"%"))


## Plot

p1 <- data_top_shares %>% ggplot(.,aes(x=year,y=share,fill=group)) +
  geom_col(color='#252525',linewidth=0.25,width=1) +
  theme_wl_bar_trend() +
  scale_fill_manual(values=c(colours_top6,"Rest of world" = "#818181ff","Least Developed Countries"="#9467bdff")) +
  scale_x_continuous(breaks=c(1990,2000,2010,max(data_top_shares$year)),
                     expand = expansion(mult = c(0.05, 0.01))) +
  theme(axis.title = element_blank(),
        legend.position = "none") +
  labs(title="Share of total greenhouse gas emissions",
       subtitle=expression("%"),
       caption="⌂ UNEP Emissions Gap Report 2024   ⌂ Data: EDGARv9, GCB 2023 \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on bookkeeping conventions")



p2 <- labels %>% 
  ggplot(.,aes(x=1,y=label_position,label=str_wrap(label,20),color=group)) +
  geom_text_repel(
    hjust=0,
    direction = "y",
    point.size = NA,
    size=3.5,
    show.legend = FALSE,
    min.segment.length = Inf,
    box.padding = 0.2,
    force = 0.1,
    lineheight=0.9) +
  annotation_custom(grob = textGrob("Share in 2022:",
                                    x = unit(0.03, "npc"), y = unit(0.91, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.9)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=c(colours_top6,"Rest of world" = "#818181ff","Least Developed Countries"="#9467bdff")) +
  scale_y_continuous(limits = c(0,100)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
  theme_wl_empty()

plot <- p1 + p2 + plot_layout(widths=c(5,1.5))
plot


ggsave(plot,filename = "UNEP-EGR-2024-top-shares.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-top-shares.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-top-shares.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_top_shares %>% ungroup() %>% select(group,year,value=share) %>%  mutate(units="% of total"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-top-shares.xlsx"),overwrite=T)

```

### Shares of annual total (G20)

``` {r top_emitter_shares, fig.height = 4, fig.width = 7}

## Aggregate emissions data

data_top_shares <- data_edgar %>% 
  filter(year>=1990) %>% 
  filter(year<=2022) %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## Join land use change (LULUCF) emissions from GCB

data_top_shares <- data_top_shares %>% 
  left_join(.,data_gcb_luc %>% select(iso,year,value_luc=value),
            by = join_by(iso, year)) %>% 
  rowwise() %>% 
  mutate(value = sum(value, value_luc, na.rm = TRUE)) %>%
  ungroup() %>% 
  select(-value_luc)

data_top_shares <- data_top_shares %>% 
  mutate(value=value/1e9)

## Join EU

data_top_shares_eu <- left_join(data_top_shares,cc_EU,by="iso") %>%
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27") %>% 
  select(-EU) %>%
  mutate(country="European Union") %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=T)) %>% 
  ungroup()

data_top_shares <- left_join(data_top_shares,cc_EU,by="iso") %>% 
  filter(is.na(EU)) %>% 
  bind_rows(.,data_top_shares_eu) %>% 
  select(-EU)


# ## Merge LDCs
# 
# data_top_shares_ldcs <- left_join(data_top_shares,cc_LDC,by="iso") %>%
#   filter(!is.na(LDC)) %>% 
#   mutate(iso="LDCS") %>% 
#   select(-LDC) %>%
#   mutate(country="Least Developed Countries") %>% 
#   group_by(iso,country,year) %>% 
#   summarise(value=sum(value,na.rm=T)) %>% 
#   ungroup()
# 
# data_top_shares <- left_join(data_top_shares,cc_LDC,by="iso") %>% 
#   filter(is.na(LDC)) %>% 
#   bind_rows(.,data_top_shares_ldcs) %>% 
#   select(-LDC)


## Get G20 and Annex I

data_top_shares <- data_top_shares %>% 
  left_join(.,read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/g20.csv") %>%
              select(iso=Code) %>% 
              mutate(G20="1")) %>% 
  left_join(.,read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/annex-one.csv") %>%
              select(iso=Code) %>% 
              mutate(AnnexI="1")) %>% 
  mutate(G20=ifelse(iso=="EU27","1",G20)) %>% 
  mutate(AnnexI=ifelse(iso=="EU27","1",AnnexI))


## Get top x countries + LDCs

data_top_shares <- data_top_shares %>% 
  mutate(group=ifelse(G20=="1" & AnnexI=="1","G20 (Annex I)",NA)) %>% 
  mutate(group=ifelse(G20=="1" & is.na(AnnexI),"G20 (non-Annex I)",group)) %>% 
  mutate(group=ifelse(is.na(G20),"Non-G20",group))


## Group 

data_top_shares <- data_top_shares %>% 
  group_by(group,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## Arrange factor levels

data_top_shares$group <- as.factor(data_top_shares$group)
#data_top_shares$group <- fct_reorder(data_top_shares$group)
#data_top_shares <- data_top_shares %>% arrange(group)


## Calculate shares

data_top_shares <- data_top_shares %>% 
  left_join(.,data_top_shares %>% 
              group_by(year) %>% 
              summarise(total=sum(value,na.rm=T)),by="year") %>% 
  mutate(share=100*(value/total))


## Calculate label positions

labels <- data_top_shares %>% 
  filter(year==2022) %>% 
  ungroup() %>% 
  arrange(desc(group)) %>% 
  mutate(label_position=share) %>%
  mutate(label_position=cumsum(label_position)) %>% 
  mutate(label_position=label_position-(share/2)) %>% 
  mutate(label=paste0(group," ",round(share),"%"))


## Plot

p1 <- data_top_shares %>% ggplot(.,aes(x=year,y=share,fill=group)) +
  geom_col(color='#252525',linewidth=0.25,width=1) +
  theme_wl_bar_trend() +
  scale_fill_manual(values=c("G20 (Annex I)" = "#659cccff","G20 (non-Annex I)" = "#17becfff","Non-G20"="#ff9055ff")) +
  scale_x_continuous(breaks=c(1990,2000,2010,max(data_top_shares$year)),
                     expand = expansion(mult = c(0.05, 0.01))) +
  theme(axis.title = element_blank(),
        legend.position = "none") +
  labs(title="Share of total greenhouse gas emissions",
       subtitle=expression("%"),
       caption="⌂ UNEP Emissions Gap Report 2024   ⌂ Data: EDGARv9, GCB 2023 \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on bookkeeping conventions; \nG20 excludes the African Union")


p2 <- labels %>% 
  ggplot(.,aes(x=1,y=label_position,label=str_wrap(label,21),color=group)) +
  geom_text_repel(
    hjust=0,
    direction = "y",
    point.size = NA,
    size=3.5,
    show.legend = FALSE,
    min.segment.length = Inf,
    box.padding = 0.2,
    force = 0.1,
    lineheight=0.9) +
  annotation_custom(grob = textGrob("Share in 2022:",
                                    x = unit(0.03, "npc"), y = unit(0.91, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.9)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=c("G20 (Annex I)" = "#659cccff","G20 (non-Annex I)" = "#17becfff","Non-G20"="#ff9055ff")) +
  scale_y_continuous(limits = c(0,100)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
  theme_wl_empty()

plot <- p1 + p2 + plot_layout(widths=c(5,1.5))
plot


ggsave(plot,filename = "UNEP-EGR-2024-G20-shares.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-G20-shares.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-G20-shares.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
# writeData(wb, sheet = "data",data_top_shares %>% ungroup() %>% select(group,year,value=share) %>%  mutate(units="% of total"),colNames = T, rowNames = F)
writeData(wb, sheet = "data",data_top_shares,colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-G20-shares.xlsx"),overwrite=T)

```

### Shares of cumulative total

``` {r top_emitter_shares, fig.height = 4, fig.width = 8}

## Aggregate emissions data

data_top_shares <- data_gcb_co2_ffi %>% 
  filter(year>=1850) %>% 
  filter(year<=2022) %>% 
  group_by(iso,country,year) %>% 
  summarise(value_ffi=sum(value,na.rm=TRUE))


## Join land use change (LULUCF) emissions from GCB

data_top_shares <- data_top_shares %>% 
  left_join(.,data_gcb_luc %>% select(iso,year,value_luc=value),
            by = join_by(iso, year)) %>% 
  rowwise() %>% 
  mutate(value_luc=value_luc/1e9) %>% 
  mutate(value_tot = sum(value_ffi, value_luc, na.rm = TRUE)) %>%
  ungroup()


## Join EU

data_top_shares_eu <- left_join(data_top_shares,cc_EU,by="iso") %>%
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27") %>% 
  select(-EU) %>%
  mutate(country="European Union") %>% 
  group_by(iso,country,year) %>% 
  summarise(value_ffi=sum(value_ffi,na.rm=T),
            value_luc=sum(value_luc,na.rm=T),
            value_tot=sum(value_tot,na.rm=T)) %>% 
  ungroup()

data_top_shares <- left_join(data_top_shares,cc_EU,by="iso") %>% 
  filter(is.na(EU)) %>% 
  bind_rows(.,data_top_shares_eu) %>% 
  select(-EU)


## Merge LDCs

data_top_shares_ldcs <- left_join(data_top_shares,cc_LDC,by="iso") %>%
  filter(!is.na(LDC)) %>% 
  mutate(iso="LDCS") %>% 
  select(-LDC) %>%
  mutate(country="Least Developed Countries") %>% 
  group_by(iso,country,year) %>% 
  summarise(value_ffi=sum(value_ffi,na.rm=T),
            value_luc=sum(value_luc,na.rm=T),
            value_tot=sum(value_tot,na.rm=T)) %>% 
  ungroup()

data_top_shares <- left_join(data_top_shares,cc_LDC,by="iso") %>% 
  filter(is.na(LDC)) %>% 
  bind_rows(.,data_top_shares_ldcs) %>% 
  select(-LDC)


## Calculate cumulative emissions up to each year

data_top_shares <- data_top_shares %>% 
  filter(!is.na(iso)) %>% 
  group_by(iso,country) %>%
  arrange(year) %>%
  mutate(cumulative_value_tot = cumsum(value_tot)) %>%
  ungroup()


## Get top x countries + LDCs

# countries <- data_top_shares %>%
#   ungroup() %>%
#   filter(year==2022) %>%
#   filter(iso!="LDCS") %>%
#   arrange(desc(cumulative_value_tot)) %>%
#   head(6) %>%
#   mutate(rank=1) %>%
#   mutate(rank=cumsum(rank)) %>%
#   mutate(group=country) %>%
#   select(iso,group,rank) %>%
#   add_row(iso="LDCS",group="Least Developed Countries",rank=8)


countries <- data_top_shares %>%
  ungroup() %>%
  filter(year==2022) %>%
  filter(iso!="LDCS") %>%
  filter(country %in% high_emitters) %>% 
  arrange(desc(cumulative_value_tot)) %>%
  mutate(rank=1) %>%
  mutate(rank=cumsum(rank)) %>%
  mutate(group=country) %>%
  select(iso,group,rank) %>%
  add_row(iso="LDCS",group="Least Developed Countries",rank=8)


## Group rest of world

data_top_shares <- left_join(data_top_shares,countries,by="iso") %>% 
  mutate(group=ifelse(is.na(group),"Rest of world",group)) %>% 
  mutate(rank=ifelse(group=="Rest of world",7,rank))

data_top_shares_rest <- data_top_shares %>% 
  filter(group=="Rest of world") %>% 
  group_by(group,rank,year) %>% 
  summarise(value_ffi=sum(value_ffi,na.rm=T),
            value_luc=sum(value_luc,na.rm=T),
            value_tot=sum(value_tot,na.rm=T),
            cumulative_value_tot=sum(cumulative_value_tot,na.rm=TRUE))

data_top_shares <- data_top_shares %>%
  filter(group!="Rest of world") %>% 
  bind_rows(.,data_top_shares_rest)

data_top_shares <- data_top_shares %>% 
  select(-iso,-country) %>% 
  select(year,rank,group,everything()) %>% 
  arrange(year,rank,group)


## Calculate global totals and group shares

data_top_shares <- data_top_shares %>% 
  group_by(year) %>% 
  mutate(cumulative_value_global=sum(cumulative_value_tot)) %>% 
  ungroup() %>% 
  mutate(share=100*cumulative_value_tot/cumulative_value_global)

## Arrange factor levels

data_top_shares$group <- as.factor(data_top_shares$group)
data_top_shares$group <- fct_reorder(data_top_shares$group,data_top_shares$rank)
#data_top_shares <- data_top_shares %>% arrange(group)


## Calculate label positions

labels <- data_top_shares %>% 
  filter(year==2022) %>% 
  ungroup() %>% 
  arrange(desc(group)) %>% 
  mutate(label_position=share) %>%
  mutate(label_position=cumsum(label_position)) %>% 
  mutate(label_position=label_position-(share/2)) %>% 
  mutate(label=paste0(group," ",round(share),"%"))


## Plot

p1 <- data_top_shares %>% ggplot(.,aes(x=year,y=share,fill=group)) +
  geom_area(color='#252525',linewidth=0.25,width=1) +
  theme_wl_bar_trend() +
  scale_fill_manual(values=c(colours_top6,"Rest of world" = "#818181ff","Least Developed Countries"="#9467bdff",
                               "United Kingdom"="#d45087ff")) +
  theme(axis.title = element_blank(),
        legend.position = "none") +
  labs(title=bquote(paste("Share of cumulative CO"[2]," emissions")),
       subtitle=expression("%"),
       caption="⌂ UNEP Emissions Gap Report 2024   ⌂ Data: GCB 2023 \n⌂ Note: Includes fossil and net land use change (LULUCF) emissions, with the latter based on bookkeeping conventions")

default_breaks <- ggplot_build(p1)$layout$panel_params[[1]]$x$breaks
p1 <- p1 + scale_x_continuous(breaks = c(default_breaks,2022),expand = expansion(mult = c(0.025, 0.01))) 

p2 <- labels %>% 
  ggplot(.,aes(x=1,y=label_position,label=str_wrap(label,20),color=group)) +
  geom_text_repel(
    hjust=0,
    direction = "y",
    point.size = NA,
    size=3.5,
    show.legend = FALSE,
    min.segment.length = Inf,
    box.padding = 0.2,
    force = 0.1,
    lineheight=0.9) +
  annotation_custom(grob = textGrob("Share in 2022:",
                                    x = unit(0.03, "npc"), y = unit(0.91, "npc"),hjust = 0, vjust = 0,
                                    gp = gpar(col = "#636363", fontsize = 10, lineheight=0.9)),
                    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  scale_colour_manual(values=c(colours_top6,"Rest of world" = "#818181ff","Least Developed Countries"="#9467bdff",
                               "United Kingdom"="#d45087ff")) +
  scale_y_continuous(limits = c(0,100)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.05))) +
  theme_wl_empty()

plot <- p1 + p2 + plot_layout(widths=c(5,1.5))
plot


ggsave(plot,filename = "UNEP-EGR-2024-top-shares-co2.png",path = "results/standard/",device = "png",height = 4,width=8,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-top-shares-co2.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=8)
ggsave(plot,filename = "UNEP-EGR-2024-top-shares-co2.svg",path = "results/standard/",device = 'svg',height = 4,width=8)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_top_shares %>%  mutate(units="% of total"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-top-shares-co2.xlsx"),overwrite=T)

```

### Contribution to total change

``` {r top6_contribution,fig.height=4,fig.width=7.5}


## Aggregate emissions

data_contribution <- data_edgar %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=T)/1e6) %>% 
  filter(year %in% c(max(data_edgar$year),max(data_edgar$year)-1))


## Aggregate EU

data_contribution_eu <- data_contribution %>% 
  left_join(.,cc_EU,by="iso") %>% 
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27",country="European Union") %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value))

data_contribution <- data_contribution %>% 
  left_join(.,cc_EU,by="iso") %>% 
  filter(is.na(EU)) %>% 
  rbind(.,data_contribution_eu) %>% 
  select(-EU)


## Aggregate intl. transport

# data_contribution <- data_contribution %>%
#   mutate(iso=ifelse(iso=="AIR","AIRSEA",iso)) %>%
#   mutate(iso=ifelse(iso=="SEA","AIRSEA",iso)) %>%
#   mutate(country=ifelse(country=="Intl. Aviation","Intl. Transport",country)) %>%
#   mutate(country=ifelse(country=="Intl. Shipping","Intl. Transport",country)) %>%
#   group_by(iso,country,year) %>%
#   summarise(value=sum(value,na.rm=T))


## Join land use change

data_contribution_luc <- data_gcb_luc %>% 
  filter(country=="Global") %>% 
  mutate(value=value/1e6)

# Add the GCB projection for 2023 (https://essd.copernicus.org/articles/15/5301/2023/) and join

data_contribution_luc <- data_contribution_luc %>% 
  add_row(year=2023,value=1.1*(44/12)*1000) %>% 
  mutate(iso="LUC",country="Land use change (LULUCF)") %>% 
  filter(year %in% c(max(data_edgar$year),max(data_edgar$year)-1))

data_contribution <- rbind(data_contribution,data_contribution_luc)


## Include top6 by current emissions + transport + luc and aggregate rest of world

data_contribution <- data_contribution %>% 
  mutate(group=ifelse(country %in% c(high_emitters,"Intl. Transport","Land use change (LULUCF)"),1,0)) %>% 
  mutate(iso=ifelse(group==0,"REST",iso)) %>% 
  mutate(country=ifelse(group==0,"Rest of World",country)) %>% 
  group_by(iso,country,year) %>% 
  summarise(value=sum(value,na.rm=T))


## Calculate changes and rank

data_contribution <- data_contribution %>% 
  group_by(iso) %>% 
  mutate(change_abs=last(value)-first(value),
         change_rel=change_abs/first(value))


# Re-arrange order of countries so that net additions come first, net reductions last

data_contribution_order <- data_contribution %>% 
  ungroup() %>% 
  filter(year==max(data_contribution$year)) %>% 
  mutate(change_abs=ifelse(iso=="REST",0,change_abs)) %>% 
  arrange(desc(change_abs)) %>% 
  mutate(order=row_number()) %>% 
  select(iso,order)

data_contribution <- left_join(data_contribution,data_contribution_order,by=join_by(iso)) %>% 
  arrange(order,year)



# add total emissions before

data_contribution <- data_contribution %>% 
  bind_rows(.,data.frame(country="2022 Emissions",
                         change_abs=sum(data_contribution$value[data_contribution$year==max(data_contribution$year)-1]),
                         order=0,
                         year=max(data_contribution$year)-1))



# add total emissions after

data_contribution <- data_contribution %>% 
  bind_rows(.,data.frame(country="2023 Emissions",
                         change_abs=sum(data_contribution$value[data_contribution$year==max(data_contribution$year,na.rm=T)],na.rm=T),
                         order=max(data_contribution$order)+1,
                         year=max(data_contribution$year)-1))


data_contribution <- data_contribution  %>% 
  filter(year==max(data_contribution$year)-1) %>%
  arrange(order) %>% 
  ungroup() %>% 
  mutate(end = cumsum(change_abs),
         start = c(0, head(end, -1))) %>% 
  mutate(end = ifelse(order==max(data_contribution$order),change_abs,end),
         start = ifelse(order==max(data_contribution$order),0,start))



data_contribution$country <- as.factor(data_contribution$country)
data_contribution$country <- fct_reorder(data_contribution$country,data_contribution$order)


data_contribution <- data_contribution %>%
  mutate(order=order+1) %>% 
  mutate(labels=signif(change_abs,3)) %>% 
  mutate(labels=ifelse(start!=0 & labels>0,paste0("+",labels),labels))




plot <- data_contribution %>% ggplot(.,aes(fill = country)) +
  geom_rect(aes(x = country,xmin = order - 0.2, xmax = order + 0.2, ymin = end, ymax = start),
            color="#252525",linewidth=0.25) +
  geom_segment(data=data_contribution %>% filter(order!=10),
               aes(x = order + 0.2, xend = order + 0.8,y = end, yend = end),
               color = "#252525",linewidth=0.25) +
  
  geom_text(aes(x=country,y=ifelse(change_abs>0,end+100,end+100-change_abs),label=labels),
            color="#636363",
            size=3.5) +
  
  coord_cartesian(ylim=c(56000,58000))+
  scale_x_discrete(labels = function(x) str_wrap(x, width = 12)) +
  scale_fill_manual(values=c(colours_top6,"Rest of World"="#9467bdff","Land use change (LULUCF)"="#4f8455ff")) +
  theme_wl() +
  theme(legend.position="none",
        axis.title = element_blank(),
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(vjust = 1),plot.title = element_text(margin=margin(t=15))) +
  labs(title="Contributions to the change in 2023 greenhouse gas emissions",
       subtitle=bquote(paste("MtCO"[2], "e/year")),
       caption="⌂ UNEP Emissions Gap Report 2024   ⌂ Data: EDGARv9, GCB 2023 \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on bookkeeping conventions")


plot


ggsave(plot,filename = "UNEP-EGR-2024-top-contribution.png",path = "results/standard/",device = "png",height = 4,width=7.5,dpi=300)
ggsave(plot,filename = "UNEP-EGR-2024-top-contribution.pdf",path = "results/standard/",device = cairo_pdf,height = 4,width=7.5)
ggsave(plot,filename = "UNEP-EGR-2024-top-contribution.svg",path = "results/standard/",device = 'svg',height = 4,width=7.5)


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); GCB 2023 (https://globalcarbonbudget.org/carbonbudget2023/)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_contribution %>% filter(!is.na(iso)) %>% select(iso,country,change_abs) %>% mutate(units="MtCO2e"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/UNEP-EGR-2024-top-contribution.xlsx"),overwrite=T)




```

## Country plots
### Trend by sector

``` {r countries_trend, fig.height=4, fig.width=8}

## Aggregate emissions

data_countries <- data_edgar %>% 
  group_by(iso,country,sector_lv2,sector_lv2_order,year) %>% 
  summarise(value=sum(value,na.rm=T)/1e6) %>% 
  filter(year>=1990)


## Grassi et al. LULUCF data (https://zenodo.org/records/7190601)

data_countries_luc <- read.xlsx('sources/not public/Grassi_et_al_LULUCF.xlsx')
data_countries_luc <- gather(data_countries_luc,year,value,-country,-iso)
data_countries_luc <- data_countries_luc %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(!is.na(year)) %>% 
  mutate(value=value) %>% 
  mutate(sector_lv2="Land use change (LULUCF)") %>% 
  select(iso,sector_lv2,year,value)

data_countries_luc_2 <- read.xlsx('sources/not public/LULUCF NGHGI data for UNEP 2024.xlsx',startRow = 3) %>% 
  rename(category=LAND.CATEGORY,country=UNFCCC.country,iso=country.code)
data_countries_luc_2 <- gather(data_countries_luc_2,year,value,`2000`:`2023`) %>% 
  filter(category=="LULUCF net") %>% 
  mutate(value=value) %>%
  mutate(year=as.numeric(year)) %>% 
  mutate(sector_lv2="Land use change (LULUCF)") %>% 
  filter(!is.na(year)) %>% 
  filter(!is.na(iso)) %>% 
  select(iso,sector_lv2,year,value)

data_countries_luc <- rbind(data_countries_luc %>% filter(year<2000),data_countries_luc_2) %>% 
  mutate(sector_lv2_order=8)

data_countries <- rbind(data_countries,data_countries_luc)

data_countries <- data_countries %>% 
  ungroup() %>% 
  arrange(iso,year) %>% 
  mutate(country=na.locf(country))


## Add Europe

data_countries_eu <- data_countries %>% 
  left_join(.,cc_EU,by="iso") %>% 
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27",country="European Union") %>% 
  group_by(iso,country,sector_lv2,sector_lv2_order,year) %>% 
  summarise(value=sum(value))

data_countries <- rbind(data_countries,data_countries_eu)



data_countries$sector_lv2 <- as.factor(data_countries$sector_lv2)
data_countries$sector_lv2 <- fct_reorder(data_countries$sector_lv2,data_countries$sector_lv2_order)

data_countries <- data_countries %>% 
  arrange(iso,country,sector_lv2,year)

##

plot_country <- function(countries,data_countries) {
  
  data_countries <- data_countries %>% 
    filter(country==countries)
  
  totals <- data_countries %>% 
    group_by(year) %>% 
    summarise(value=sum(value,na.rm=T)) %>% 
    filter(year >= max(data_countries$year)-3) %>%
    ungroup() %>% 
    mutate(change=growth_rate(year,value)$rate) %>% 
    mutate(change=change*100) %>% 
    mutate(change=signif(change,2)) %>% 
    mutate(change=ifelse(change>0,paste0("+",change,"%"),paste0("-",abs(change),"%"))) %>% 
    mutate(value=signif(value,3)) %>% 
    filter(year==max(data_countries$year))
  
  
  plot <- data_countries %>%
    ggplot(.,aes(x=year,y=value,fill=sector_lv2)) +
    geom_col(color="#252525",linewidth=0.25,width=1) +
    annotation_custom(grob = textGrob(paste0("Emissions in 2023: ",totals$value),
                                      x = unit(1.0425, "npc"), y = unit(0.02, "npc"),hjust = 0, vjust = -1,
                                      gp = gpar(col = "#636363", fontsize = 10)),
                      xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
    annotation_custom(grob = textGrob(paste0("Change since ",max(data_countries$year)-3,": ",totals$change),
                                      x = unit(1.0425, "npc"), y = unit(-0.04, "npc"),hjust = 0, vjust = -1,
                                      gp = gpar(col = "#636363", fontsize = 10)),
                      xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
    coord_cartesian(clip = "off") +
    theme_wl_bar_trend() +
    scale_fill_manual(values=colours_9_sectors) +
    #scale_y_continuous(breaks=c(0,20,40,60),limits=c(0,70)) +
    scale_x_continuous(breaks=c(1990,2000,2010,2020,max(data_countries$year)),
                       expand = expansion(mult = c(0.05, 0.01))) +
    theme(axis.title = element_blank(),
          legend.position = "right") +
    labs(title=countries,
         subtitle=bquote(paste("MtCO"[2], "e/year")),
         caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGAR v9, Grassi et al. 2024  \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on inventories")
  
  
  return(plot)
  
}


plot_country("United Kingdom",data_countries)

## Filter to G20 countries

countries <- data_countries %>% 
  select(iso,country) %>% 
  distinct() %>% 
  left_join(.,read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/g20.csv") %>%
              select(iso=Code) %>% 
              mutate(G20="1")) %>% 
  filter(G20==1)

countries <- c(countries$country,"European Union")


for (i in 1:length(countries)){
  
  plot <- plot_country(countries[i],data_countries)
  
  ggsave(plot,filename = paste0("UNEP-EGR-2024-",countries[i],"-atrend.png"),
         path = "results/standard/countries/",device = "png",height = 4,width=8,dpi=300)
  ggsave(plot,filename = paste0("UNEP-EGR-2024-",countries[i],"-atrend.pdf"),
         path = "results/standard/countries/",device = cairo_pdf,height = 4,width=8)
  ggsave(plot,filename = paste0("UNEP-EGR-2024-",countries[i],"-atrend.svg"),
         path = "results/standard/countries/",device = 'svg',height = 4,width=8)
  
}


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); Grassi et al. 2024 (https://zenodo.org/records/7190601)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_countries %>% select(-sector_lv2_order) %>% mutate(units="MtCO2e/year (GWP100 AR6)"),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/countries/UNEP-EGR-2024-country-trend.xlsx"),overwrite=T)



```

### Changes by sector

``` {r countries_changes,fig.height=4,fig.width=8}

## Aggregate emissions

data_countries_change <- data_edgar %>% 
  group_by(iso,country,sector_lv2,year) %>% 
  summarise(value=sum(value,na.rm=T)/1e6)


## Add land use change emissions

data_countries_luc <- read.xlsx('sources/not public/LULUCF NGHGI data for UNEP 2024.xlsx',startRow = 3) %>% 
  rename(category=LAND.CATEGORY,country=UNFCCC.country,iso=country.code) %>% 
  filter(category=="LULUCF net")

data_countries_luc <- gather(data_countries_luc,year,`Land use change (LULUCF)`,`2000`:`2023`) %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(!is.na(iso)) %>% 
  select(iso,year,`Land use change (LULUCF)`)

data_countries_change <- data_countries_change %>% 
  spread(.,sector_lv2,value) %>% 
  left_join(.,data_countries_luc,by=join_by(iso,year)) %>% 
  gather(.,sector_lv2,value,-iso,-country,-year)


## Add Europe

data_countries_eu <- data_countries_change %>% 
  left_join(.,cc_EU,by="iso") %>% 
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27",country="European Union") %>% 
  group_by(iso,country,sector_lv2,year) %>% 
  summarise(value=sum(value))

data_countries_change <- rbind(data_countries_change,data_countries_eu)


## Plot

plot_country_change <- function(countries,t,data_countries_change) {
  
  ## Filter
  
  data_countries_change <- data_countries_change %>% 
    filter(country==countries) %>% 
    filter(year %in% c(max(data_countries_change$year),max(data_countries_change$year)-t))
  
  
  ## Calculate changes and rank
  
  data_countries_change <- data_countries_change %>% 
    group_by(sector_lv2) %>% 
    mutate(change_abs=last(value)-first(value),
           change_rel=change_abs/first(value))
  
  
  # Re-arrange order of sectors so that net additions come first, net reductions last
  
  data_countries_change_order <- data_countries_change %>% 
    ungroup() %>% 
    filter(year==max(data_countries_change$year)) %>% 
    arrange(desc(change_abs)) %>% 
    mutate(order=row_number()) %>% 
    select(sector_lv2,order)
  
  data_countries_change <- left_join(data_countries_change,data_countries_change_order,by=join_by(sector_lv2)) %>% 
    arrange(order,year)
  
  
  ## Get totals
  
  data_countries_change_tot <- data_countries_change %>% 
    group_by(year) %>% 
    summarise(value=sum(value,na.rm=T)) %>% 
    mutate(label=paste0("Emissions in ",year,": ",signif(value,3)))
  
  
  ## Arrange data for waterfall
  
  data_countries_change <- data_countries_change  %>% 
    ungroup() %>% 
    filter(year==max(data_countries_change$year)-t) %>%
    add_row(order=0,change_abs=data_countries_change_tot$value[1]) %>% 
    arrange(order) %>% 
    ungroup() %>%
    mutate(end = cumsum(change_abs),
           start = c(0, head(end, -1))) %>% 
    filter(order!=0)
  
  
  ## Arrange levels, add labels
  data_countries_change$sector_lv2 <- gsub("\\| ","",data_countries_change$sector_lv2)
  data_countries_change$sector_lv2 <- as.factor(data_countries_change$sector_lv2)
  data_countries_change$sector_lv2 <- fct_reorder(data_countries_change$sector_lv2,data_countries_change$order)
  colours_custom <- c(
    "Energy Power" = "#17becfff",
    "Energy Industry" = "#3a5e91ff",
    "Energy Transport" = "#5185b5ff",
    "Energy Buildings & other" = "#74a6d4ff",
    "Energy Fuel production" = "#ff9055ff",
    "Industrial processes" = "#e5b82cff",
    "Agriculture" = "#4f8455ff",
    "Land use change (LULUCF)" = "#7dd396ff",
    "Waste" = "#818181ff")
  
  
  data_countries_change <- data_countries_change %>%
    mutate(labels=signif(change_abs,3)) %>% 
    mutate(labels=ifelse(labels>0,paste0("+",labels),labels))
  
  
  ## Plot
  
  
  p1 <- data_countries_change %>% 
    ggplot(.,aes(fill = sector_lv2)) +
    geom_rect(aes(x = sector_lv2,xmin = order - 0.2, xmax = order + 0.2, ymin = end, ymax = start),
              color="#252525",linewidth=0.25) +
    geom_segment(data=data_countries_change %>% filter(order!=max(data_countries_change$order)),
                 aes(x = order + 0.2, xend = order + 0.8,y = end, yend = end),
                 color = "#252525",linewidth=0.25) +
    
    # geom_text(aes(x=sector_lv2,y=ifelse(change_abs>0,end+100,end+100-change_abs),label=labels),
    #           color="#636363",
    #           size=3.5) +
    scale_x_discrete(labels = function(x) str_wrap(x, width = 10),expand = expansion(mult = c(0.05, 0.05))) +
    scale_y_continuous(breaks=data_countries_change_tot$value) +
    scale_fill_manual(values=colours_custom) +
    theme_wl() +
    theme(legend.position="none",
          axis.title = element_blank(),
          panel.grid.major.x = element_blank(),
          axis.text.x = element_text(vjust = 1),
          plot.title = element_text(margin=margin(t=15)),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank()) +
          # panel.grid.major.y = element_blank(),
          # axis.ticks.y = element_blank(),
          # axis.line.y = element_blank()) +
    labs(title=countries,
         subtitle=bquote(paste("Change in recent emissions (MtCO"[2], "e)")),
         caption="⌂ UNEP Emissions Gap Report 2024    ⌂ Data: EDGARv9, Grassi et al. 2024 \n⌂ Note: GWP100 AR6; net land use change (LULUCF) emissions based on inventories") +
    coord_cartesian(clip = "off")
  
  
  y_range_scaling <- layer_scales(p1)$y$range$range
  y_range_scaling <- diff(y_range_scaling) * 0.08
  
  
  p1 <- p1 +
    geom_text(aes(x=sector_lv2,y=ifelse(change_abs>0,end+y_range_scaling,end+y_range_scaling-change_abs),label=labels),
              color="#636363",
              size=3.5)
  
  y_range_scaling_2 <- layer_scales(p1)$y$range$range
  y_range_expanded <- y_range_scaling_2 + c(-0.001 * diff(y_range_scaling_2),0.001 * diff(y_range_scaling_2))
  
  p2 <- data_countries_change_tot %>%
    filter(year==data_countries_change_tot$year[2]) %>% 
    ggplot(.,aes(x=1.5,y=value,label=str_wrap(label,15))) +
    geom_text(size=3.5,colour="#636363",hjust=0) +
    geom_segment(aes(x = 1.4, xend = 1, yend = value),
                 arrow = arrow(length = unit(0.2, "cm")),
                 colour = "#636363") +
    scale_y_continuous(limits = y_range_expanded) +
    scale_x_continuous(limits = c(1,4.5),expand = expansion(mult = c(0, 0.05))) +
    theme_wl_empty() +
    coord_cartesian(clip = "off")
  
  p3 <- data_countries_change_tot %>%
    filter(year==data_countries_change_tot$year[1]) %>% 
    ggplot(.,aes(x=4,y=value,label=str_wrap(label,15))) +
    geom_text(size=3.5,colour="#636363",hjust=1) +
    geom_segment(aes(x = 4.1, xend = 4.5, yend = value),
                 arrow = arrow(length = unit(0.2, "cm")),
                 colour = "#636363") +
    scale_y_continuous(limits = y_range_expanded) +
    scale_x_continuous(limits = c(1,4.5),expand = expansion(mult = c(0.05, 0))) +
    theme_wl_empty() +
    coord_cartesian(clip = "off")
  
  
  plot <- plot_spacer() + p3 + plot_spacer() + p1 + plot_spacer() + p2 + plot_layout(widths=c(-0.26,1,-0.26,6,-0.26,1))
  plot
  
  
  
  return(plot)
}


plot_country_change("European Union",2,data_countries_change)


## Filter to G20 countries

countries <- data_countries_change %>%
  select(iso,country) %>%
  distinct() %>%
  left_join(.,read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/g20.csv") %>%
              select(iso=Code) %>%
              mutate(G20="1")) %>%
  filter(G20==1)

countries <- c(countries$country,"European Union")


for (i in 1:length(countries)){

  plot <- plot_country_change(countries[i],3,data_countries_change)

  ggsave(plot,filename = paste0("UNEP-EGR-2024-",countries[i],"-change.png"),
         path = "results/standard/countries/",device = "png",height = 4,width=8,dpi=300)
  ggsave(plot,filename = paste0("UNEP-EGR-2024-",countries[i],"-change.pdf"),
         path = "results/standard/countries/",device = cairo_pdf,height = 4,width=8)
  ggsave(plot,filename = paste0("UNEP-EGR-2024-",countries[i],"-change.svg"),
         path = "results/standard/countries/",device = 'svg',height = 4,width=8)

}


## Save data

wb <- createWorkbook()
addWorksheet(wb,"info")
addWorksheet(wb,"data")
info = data.frame(a=c("Author","Contact","Data sources","See also"),
                  b=c("William F. Lamb",
                      "william.lamb@pik-potsdam.de",
                      "EDGARv9 (https://edgar.jrc.ec.europa.eu/report_2024); Grassi et al. 2024 (https://zenodo.org/records/7190601)",
                      "https://lambwf.github.io/UNEP-Gap-Report-2024-Chapter-2/"))

writeData(wb, sheet = "info",info,colNames = F, rowNames = F)
writeData(wb, sheet = "data",data_countries_change %>% 
            filter(year %in% c(max(data_countries_change$year),max(data_countries_change$year)-3)) %>%
            mutate(units="MtCO2e (GWP100 AR6)") %>% 
            arrange(iso,country,year,sector_lv2),colNames = T, rowNames = F)

saveWorkbook(wb,paste0("results/standard/countries/UNEP-EGR-2024-country-change.xlsx"),overwrite=T)




```

