---
title: "UNEP-Gap-Report-2024-Differences"
author: "William F. Lamb"
date: "13 9 2024"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)

rm(list = ls())

library(tidyverse)
library(openxlsx)
library(countrycode)
library(ggrepel)
library(patchwork)
library(zoo)
library(RColorBrewer)
library(WDI)
library(labelled)
library(grid)
library(ggimage)

source("https://raw.githubusercontent.com/lambwf/Codebase/main/figure_style.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/reshape_with_labels.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/locate_shares.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_gcb_countries_v2023.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_edgar_v9.R")

wb <- createWorkbook()

```

## Load versions


```{r load_versions}

data_unep_2024 <- read.xlsx('results/UNEP-Gap-Report-2024-Chapter-2-Data-Global.xlsx',sheet=2)
data_unep_2024 <- gather(data_unep_2024,year,value,`1990`:`2023`) %>% select(gas,year,unep_2024=value) %>% mutate(year=as.numeric(year))
data_unep_2024 <- data_unep_2024 %>% 
  filter(!gas %in% c("GHG"))
data_unep_2024 <- rbind(data_unep_2024,data_unep_2024 %>% 
                          filter(gas %in% c("CO2 Fossil","CH4","N2O","F-gases","CO2 LULUCF (Bookkeeping)")) %>% 
                          group_by(year) %>% 
                          summarise(unep_2024=sum(unep_2024,na.rm=TRUE)) %>% 
                          mutate(gas="GHG"))


data_unep_2023 <- read.xlsx('../UNEP Gap Report 2023/Results/UNEP-Gap-Report-2023-Chapter-2-Global-Data.xlsx',sheet=2)
data_unep_2023 <- data_unep_2023 %>% select(gas,year,unep_2023=value)
data_unep_2023 <- data_unep_2023 %>% 
  mutate(gas=ifelse(gas=="CO2_fossil","CO2 Fossil",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_LULUCF_NGHGI","CO2 LULUCF (Inventory)",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_LULUCF_bookkeeping","CO2 LULUCF (Bookkeeping)",gas)) %>% 
  mutate(gas=ifelse(gas=="Fgas","F-gases",gas))

data_unep_2023 <- rbind(data_unep_2023,data_unep_2023 %>% 
                          filter(gas %in% c("CO2 Fossil","CH4","N2O","F-gases","CO2 LULUCF (Bookkeeping)")) %>% 
                          group_by(year) %>% 
                          summarise(unep_2023=sum(unep_2023,na.rm=TRUE)) %>% 
                          mutate(gas="GHG"))


data_unep_2022 <- read.xlsx('../UNEP Gap Report 2022/Results/egr_chapter_data.xlsx',sheet=1)
data_unep_2022 <- gather(data_unep_2022,gas,unep_2022,-year)
data_unep_2022 <- data_unep_2022 %>% 
  mutate(gas=ifelse(gas=="CO2_FFI","CO2 Fossil",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_LULUCF_NGHGI","CO2 LULUCF (Inventory)",gas)) %>% 
  mutate(gas=ifelse(gas=="CO2_LULUCF_GCB","CO2 LULUCF (Bookkeeping)",gas)) %>% 
  mutate(gas=ifelse(gas=="Fgas","F-gases",gas)) %>% 
  mutate(gas=ifelse(gas=="GHG_incl_LULUCF_GCB","GHG",gas)) %>% 
  filter(!gas %in% c('GHG_ex_LULUCF','GHG_incl_LULUCF_NGHGI'))

data <- left_join(data_unep_2022,data_unep_2023,by=join_by(year,gas))
data <- left_join(data,data_unep_2024,by=join_by(year,gas))


data_table <- gather(data,dataset,value,-year,-gas) %>% 
  filter(year==2019) %>% 
  select(-year)


uncertainties = data.frame(gas=c("CO2 Fossil","CO2 LULUCF (Bookkeeping)","CO2 LULUCF (Inventory)","CH4","N2O","F-gases"),uncertainty=c(0.08,0.7,0.7,0.3,0.6,0.3))

data_table <- left_join(data_table,uncertainties,by="gas")
data_table <- data_table %>% 
  filter(gas!="GHG") %>% 
  mutate(uncertainty_abs=value*uncertainty)

data_table <- rbind(data_table %>% select(-uncertainty),data_table %>% 
  filter(!gas %in% c("GHG","CO2 LULUCF (Inventory)")) %>% 
  mutate(uncertainty_abs=uncertainty_abs^2) %>% 
  group_by(dataset) %>% 
  summarise(value=sum(value,na.rm=TRUE),
            uncertainty_abs=sqrt(sum(uncertainty_abs,na.rm=TRUE))) %>% 
  mutate(gas="GHG"))
  

data_table <- data_table %>%
  mutate(value=ifelse(gas %in% c("GHG","CO2 Fossil","CH4"),signif(value,3),signif(value,2))) %>%
  mutate(uncertainty_abs=signif(uncertainty_abs,2))

data_table <- data_table %>%
  mutate(value=paste0(value,"±",uncertainty_abs)) %>% 
  select(-uncertainty_abs)


data_table$gas <- as.factor(data_table$gas)
data_table$gas <- fct_relevel(data_table$gas,"GHG","CO2 Fossil","CO2 LULUCF (Bookkeeping)","CO2 LULUCF (Inventory)","CH4","N2O","F-gases")




data_table <- spread(data_table,dataset,value)
write.xlsx(data_table,'results/UNEP-Gap-Report-2024-Chapter-2-Data-Differences.xlsx')


```

## Difference Plots


```{r figure_differences, echo=FALSE}

data <- gather(data,dataset,value,-year,-gas)
data$gas <- as.factor(data$gas)
data$gas <- fct_relevel(data$gas,"GHG","CO2 Fossil","CH4","N2O","F-gases","CO2 LULUCF (Bookkeeping)","CO2 LULUCF (Inventory)")

data %>% ggplot(.,aes(x=year,y=value,color=dataset,group=dataset)) +
  geom_path() +
  facet_wrap(.~gas,scales="free") +
  theme_wl()


data %>% filter(year==2019) %>% 
  ggplot(.,aes(x=dataset,y=value,fill=dataset)) +
  geom_col() +
  facet_wrap(.~gas,scales="free") +
  theme_wl() +
  theme(legend.position="none")


data %>% filter(year==2019) %>% filter(gas!="GHG") %>% 
  filter(gas!="CO2 LULUCF (Inventory)") %>% 
  ggplot(.,aes(x=dataset,y=value,fill=gas)) +
  geom_col(color="#636363") +
  theme_wl()







```


```{r load_gcb, echo=FALSE}

data_gcb <- read.csv('sources/GCB2023v43_MtCO2_flat.csv')
data_gcb <- data_gcb %>% 
  select(iso=ISO.3166.1.alpha.3,year=Year,value_gcb=Total) %>% 
  filter(year>=1990)


source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_edgar_v9.R")


edgar_co2 <- read.xlsx("sources/not public/EDGAR_2024_CO2_1970_2023_v2.xlsx",sheet=2,startRow=9)
edgar_ch4 <- read.xlsx("sources/not public/EDGAR_2024_CH4_1970_2023_v2.xlsx",sheet=2,startRow = 9)
edgar_n2o <- read.xlsx("sources/not public/EDGAR_2024_N2O_1970_2023_v2.xlsx",sheet=2,startRow = 9)
edgar_fgas <- read.xlsx("sources/not public/EDGAR_2024_F-gases_1970_2023_v2.xlsx",sheet=2,startRow = 9)
data_edgar <- load_edgar(edgar_co2,edgar_ch4,edgar_n2o,edgar_fgas)
data_edgar <- data_edgar %>% 
  filter(gas=="CO2") %>% 
  filter(fossil_bio=="fossil") %>% 
  group_by(country,iso,year) %>% 
  summarise(value_edgar=sum(value,na.rm=T)*1000/1e6) %>% 
  filter(year>=1990)


data_comparison <- left_join(data_edgar,data_gcb,by=join_by(year,iso))

rank <- data_comparison %>% 
  filter(year==2022) %>% 
  group_by(iso,country) %>% 
  summarise(value=sum(value_edgar)) %>%
  ungroup() %>% 
  arrange(desc(value)) %>% 
  mutate(rank=1) %>% 
  select(iso,rank)
rank$rank=cumsum(rank$rank)

data_comparison <- left_join(data_comparison,rank,by=join_by(iso)) 


```



``` {r figure_changes_by_sector,fig.width=7,fig.height=4,fig.path="results/",dev=c('png','pdf')}

data_changes <- data_ghg %>% 
  filter(year %in% c(2022,2023)) %>% 
  group_by(year,sector_lv2,sector_lv2_colours) %>% 
  summarise(value=sum(value,na.rm=T)/1e9)

data_changes <- spread(data_changes,year,value)
data_changes <- data_changes %>% 
  mutate(change_abs=`2023`-`2022`,
         change_rel=change_abs/`2022`)

###

data_changes <- data_ghg %>%
  filter(year >= 1990 ) %>% 
  group_by(year,sector_lv2,sector_lv2_colours) %>% 
  summarise(value=sum(value,na.rm=T)/1e9) %>% 
  mutate(change_abs=NA)
sectors <- unique(data_changes$sector_lv2)

for (j in 1:length(sectors)) {
  
for (i in 1991:2023) {
  
  data_changes$change_abs[data_changes$year==i & data_changes$sector_lv2==sectors[j]] <- 
    data_changes$value[data_changes$year==i & data_changes$sector_lv2==sectors[j]] -
    data_changes$value[data_changes$year==i-1 & data_changes$sector_lv2==sectors[j]]
  
}
}

sector_colours <- data_changes %>% select(sector_lv2,sector_lv2_colours) %>% distinct()


data_changes %>% 
  filter(year>=2015) %>% 
  mutate(year=as.factor(year)) %>% 
  ggplot(.,aes(x=year,y=change_abs,fill=sector_lv2)) +
  geom_col(color="#636363") +
  geom_hline(yintercept=0) +
  geom_point(data=data_changes %>% filter(year>=2015) %>% mutate(year=as.factor(year)) %>%  group_by(year) %>% summarise(change_abs=sum(change_abs)),
             inherit.aes=FALSE,aes(x=year,y=change_abs)) +
  scale_fill_manual(values=sector_colours$sector_lv2_colours) +
  theme_wl() +
  labs(title="Change in total emissions by year and sector",
       subtitle="GtCO2e") +
  theme(axis.title = element_blank(),
        legend.title = element_blank())




```