---
title: "UNEP-Gap-Report-2024-Countries"
author: "William F. Lamb"
date: "30 4 2024"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)

rm(list = ls())

library(tidyverse)
library(openxlsx)
library(countrycode)
library(ggrepel)
library(patchwork)
library(zoo)
library(RColorBrewer)
library(WDI)
library(labelled)
library(grid)
library(ggimage)

source("https://raw.githubusercontent.com/lambwf/Codebase/main/figure_style.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/reshape_with_labels.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/locate_shares.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_gcb_countries_v2023.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_edgar_v9.R")

wb <- createWorkbook()

```


```{r load_EDGAR}


## load EDGAR data (https://edgar.jrc.ec.europa.eu/dataset_ghg80)

edgar_co2 <- read.xlsx("sources/not public/EDGAR_2024_CO2_1970_2023_v2.xlsx",sheet=2,startRow=9)
edgar_ch4 <- read.xlsx("sources/not public/EDGAR_2024_CH4_1970_2023_v2.xlsx",sheet=2,startRow = 9)
edgar_n2o <- read.xlsx("sources/not public/EDGAR_2024_N2O_1970_2023_v2.xlsx",sheet=2,startRow = 9)
edgar_fgas <- read.xlsx("sources/not public/EDGAR_2024_F-gases_1970_2023_v2.xlsx",sheet=2,startRow = 9)
data_ghg <- load_edgar(edgar_co2,edgar_ch4,edgar_n2o,edgar_fgas)


## join GWPs and calculate CO2e

gwps <- read.csv("https://raw.githubusercontent.com/openclimatedata/globalwarmingpotentials/main/globalwarmingpotentials.csv",skip = 10)

data_ghg$gas <- gsub("-","",data_ghg$gas)
data_ghg <- left_join(data_ghg,gwps %>% select(gas=Species,AR6GWP100)) %>% 
  mutate(AR6GWP100=ifelse(gas=="CO2",1,AR6GWP100))

## remove biogenic CO2

data_ghg <- data_ghg %>% 
  filter(gas!="CO2bio")


## check all gwps joined

check <- data_ghg %>% filter(is.na(AR6GWP100))
check <- data_ghg %>% select(gas,AR6GWP100) %>% distinct()

data_ghg <- data_ghg %>% mutate(value_gwp=value*AR6GWP100)


list_fgases <- data_ghg %>% 
  select(gas) %>% 
  distinct() %>% 
  mutate(group=ifelse(gas=="CO2","CO2 Fossil",NA)) %>% 
  mutate(group=ifelse(gas=="CH4","CH4",group)) %>% 
  mutate(group=ifelse(gas=="N2O","N2O",group)) %>% 
  mutate(group=ifelse(is.na(group),"F-gases",group))

data_ghg <- left_join(data_ghg,list_fgases,by="gas")
data_ghg <- data_ghg %>% 
  mutate(gas=group) %>% 
  group_by(iso,country,code,code_description,gas,year) %>% 
  summarise(value=sum(value_gwp,na.rm=TRUE))

## Gg to tons

data_ghg$value = data_ghg$value*1000


## Grassi et al. LULUCF data (https://zenodo.org/records/7190601)

data_lulucf <- read.xlsx('sources/not public/Grassi_et_al_LULUCF.xlsx')
data_lulucf <- gather(data_lulucf,year,value,-country,-iso)
data_lulucf <- data_lulucf %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(!is.na(year)) %>% 
  mutate(value=value*1e6) %>% 
  mutate(code="3B") %>% 
  mutate(code_description="Land use change") %>% 
  mutate(gas="CO2 LULUCF") %>% 
  select(iso,country,code,code_description,gas,year,value) %>% 
  filter(year<=2021)

data_lulucf_v2 <- read.xlsx('sources/not public/LULUCF NGHGI data for UNEP 2024.xlsx',startRow = 3) %>% 
  rename(category=LAND.CATEGORY,country=UNFCCC.country,iso=country.code)
data_lulucf_v2 <- gather(data_lulucf_v2,year,value,`2000`:`2023`) %>% 
  filter(category=="LULUCF net") %>% 
  mutate(value=value*1e6) %>%
  mutate(year=as.numeric(year)) %>% 
  mutate(gas="CO2 LULUCF") %>% 
  mutate(code="3B") %>% 
  mutate(code_description="Land use change") %>% 
  filter(!is.na(year)) %>% 
  filter(!is.na(iso)) %>% 
  select(iso,country,code,code_description,gas,year,value) %>% 
  filter(year<=2021)

data_lulucf <- rbind(data_lulucf %>% filter(year<2000),data_lulucf_v2)
data_lulucf <- data_lulucf %>% 
  arrange(country,iso,year)

data_ghg <- rbind(data_ghg,data_lulucf)


### consistent names

newnames <- data_ghg %>% 
  ungroup() %>% 
  select(iso) %>% 
  distinct() %>% 
  mutate(newname=countrycode(iso,"iso3c","country.name")) %>% 
  mutate(newname=ifelse(iso=="AIR","Intl. Aviation",newname)) %>% 
  mutate(newname=ifelse(iso=="SEA","Intl. Shipping",newname)) %>% 
  mutate(newname=ifelse(iso=="SCG","Serbia and Montenegro",newname)) %>% 
  mutate(newname=ifelse(iso=="ANT","Netherlands Antilles",newname)) %>% 
  mutate(newname=ifelse(iso=="WLD","World",newname))

data_ghg <- left_join(data_ghg,newnames,by="iso") %>% 
  mutate(country=newname) %>% 
  select(-newname) %>% 
  filter(!is.na(iso))

## aggregate world

data_ghg_world <- data_ghg %>% 
  filter(iso!="WLD") %>% 
  filter(gas!="CO2 LULUCF") %>% 
  group_by(code,code_description,gas,year) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(iso="WLD") %>% 
  mutate(country="World")

data_ghg <- rbind(data_ghg,data_ghg_world)

## aggregate sectors

data_ghg <- left_join(data_ghg,read.xlsx("sources/cc_sectors.xlsx"),by=join_by(code, code_description))

data_ghg$gas <- as.factor(data_ghg$gas)
data_ghg$gas <- fct_relevel(data_ghg$gas,"CO2 Fossil","CO2 LULUCF","CH4","N2O","F-gases")

data_ghg$sector_lv1 <- as.factor(data_ghg$sector_lv1)
data_ghg$sector_lv1 <- fct_reorder(data_ghg$sector_lv1,data_ghg$sector_lv1_order)

data_ghg$sector_lv2 <- as.factor(data_ghg$sector_lv2)
data_ghg$sector_lv2 <- fct_reorder(data_ghg$sector_lv2,data_ghg$sector_lv2_order)

data_ghg$sector_lv2 <- as.factor(data_ghg$sector_lv2)
data_ghg$sector_lv2 <- fct_reorder(data_ghg$sector_lv2,data_ghg$sector_lv2_order)

data_ghg$sector_lv3 <- as.factor(data_ghg$sector_lv3)
data_ghg$sector_lv3 <- fct_reorder(data_ghg$sector_lv3,data_ghg$sector_lv3_order)


data_ghg <- data_ghg %>% 
  group_by(across(c(-code,-code_description,-sector_lv2_codes,-sector_lv3_codes))) %>% 
  summarise(value=sum(value,na.rm=TRUE))


```

``` {r aggregates}

## aggregate EU

cc_EU <- read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/european-union.csv") %>% 
  select(iso=Code) %>% 
  mutate(EU="1")

data_ghg_eu <- left_join(data_ghg,cc_EU,by="iso") %>%
  filter(!is.na(EU)) %>% 
  mutate(iso="EU27") %>% 
  select(-EU) %>%
  mutate(country="European Union") %>% 
  group_by(across(c(-value))) %>% 
  summarise(value=sum(value,na.rm=T))

data_ghg_eu <- rbind(data_ghg_eu,data_ghg %>% 
                       filter(iso=="EUR") %>% 
                       filter(sector_lv2=="AFOLU: LULUCF") %>% 
                       mutate(iso="EU27") %>% 
                       mutate(country="European Union"))

data_ghg <- rbind(data_ghg %>% filter(iso!="EUR"),data_ghg_eu)


## aggregate African Union

cc_AU <- read.xlsx("sources/cc_African_Union.xlsx") %>% 
  select(iso) %>% 
  mutate(AU="1")

data_ghg_au <- left_join(data_ghg,cc_AU,by="iso") %>%
  filter(!is.na(AU)) %>% 
  mutate(iso="AU55") %>% 
  select(-AU) %>%
  mutate(country="African Union") %>% 
  group_by(across(c(-value))) %>% 
  summarise(value=sum(value,na.rm=T))

data_ghg <- rbind(data_ghg,data_ghg_au)


## aggregate G7

cc_G7 <- read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/g7.csv") %>% 
  select(iso=Code) %>% 
  mutate(G7="1") %>% 
  mutate(iso=ifelse(iso=="EUU","EU27",iso)) %>% 
  filter(!iso %in% c("FRA","DEU","ITA"))                  ## no double counting EU countries!

data_ghg_g7 <- left_join(data_ghg,cc_G7,by="iso") %>%
  filter(!is.na(G7)) %>% 
  mutate(iso="G7") %>% 
  select(-G7) %>%
  mutate(country="G7 Countries") %>% 
  group_by(across(c(-value))) %>% 
  summarise(value=sum(value,na.rm=T))

data_ghg <- rbind(data_ghg,data_ghg_g7)


## aggregate G20

cc_G20 <- read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/main/data/g20.csv") %>% 
  select(iso=Code) %>% 
  mutate(G20="1") %>% 
  mutate(iso=ifelse(iso=="EUU","EU27",iso)) %>%
  #add_row(iso="AU55",G20="1") %>% 
  #filter(!iso %in% c("ZAF")) %>%                          ## no double counting AU countries!
  filter(!iso %in% c("FRA","DEU","ITA"))                  ## no double counting EU countries!

data_ghg_g20 <- left_join(data_ghg,cc_G20,by="iso") %>%
  filter(!is.na(G20)) %>% 
  mutate(iso="G20") %>% 
  select(-G20) %>%
  mutate(country="G20 Countries") %>% 
  group_by(across(c(-value))) %>% 
  summarise(value=sum(value,na.rm=T))

data_ghg <- rbind(data_ghg,data_ghg_g20)


## aggregate non-G20

# data_ghg_ng20 <- left_join(data_ghg,cc_G20,by="iso")
# data_ghg_ng20 <- left_join(data_ghg_ng20,cc_EU,by="iso")
# #data_ghg_ng20 <- left_join(data_ghg_ng20,cc_AU,by="iso")
# data_ghg_ng20 <- data_ghg_ng20 %>% 
#   filter(is.na(G20)) %>% 
#   filter(is.na(EU)) %>% 
# #  filter(is.na(AU)) %>% 
#   filter(!iso %in% c("AIR","SEA","G7","G20","AU55","WLD"))
# 
# cc_nG20 <- data_ghg_ng20 %>% 
#   ungroup() %>% 
#   select(iso) %>% 
#   distinct() %>% 
#   mutate(nG20="1")
# 
# data_ghg_ng20 <- data_ghg_ng20 %>% 
#   mutate(iso="Non-G20") %>% 
#   select(-G20,-EU,-AU) %>%
#   mutate(country="Non-G20 Countries") %>% 
#   group_by(across(c(-value))) %>% 
#   summarise(value=sum(value,na.rm=T))
# 
# data_ghg <- rbind(data_ghg,data_ghg_ng20)


cc_aggregates <- data_ghg %>%
  ungroup() %>% 
  select(iso,country) %>% 
  distinct()

cc_aggregates <- left_join(cc_aggregates,cc_AU,by="iso")
cc_aggregates <- left_join(cc_aggregates,cc_EU,by="iso")
cc_aggregates <- left_join(cc_aggregates,cc_G20,by="iso")
cc_aggregates <- left_join(cc_aggregates,cc_G7,by="iso")
#cc_aggregates <- left_join(cc_aggregates,cc_nG20,by="iso")
cc_aggregates <- cc_aggregates %>% 
  mutate(G20=ifelse(!is.na(EU),"1",G20)) %>% 
  mutate(G20=ifelse(!is.na(AU),"1",G20))
cc_aggregates <- gather(cc_aggregates,var,value,-iso,-country) %>% 
  mutate(value=ifelse(value=="1","x",NA))
cc_aggregates <- spread(cc_aggregates,var,value)


data_ghg <- data_ghg %>%
  arrange(iso,country,gas,year,sector_lv2)


```

``` {r edgar_inventory_comparison}

data_countries <- data_ghg %>%
  filter(iso!="AU55") %>% 
  filter(gas!="CO2 LULUCF") %>% 
  group_by(iso,country,year,gas) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(dataset="EDGARv9")

data_primap <- read.csv("sources/Guetschow_et_al_2024-PRIMAP-hist_v2.5.1_final_27-Feb-2024.csv")
data_primap <- gather(data_primap,year,value,X1750:X2022)
data_primap$year <- gsub("X","",data_primap$year)
names(data_primap) <- c("source","scenario","provenance","area","gas","unit","category","year","value") 
data_primap <- data_primap %>% 
  filter(category=="M.0.EL") %>% 
  filter(scenario=="HISTCR") %>% 
  filter(gas %in% c("CO2","CH4","N2O","FGASES (AR6GWP100)")) %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(year>=1970)

data_primap <- left_join(data_primap,gwps %>% select(gas=Species,AR6GWP100))
data_primap <- data_primap %>% 
  mutate(AR6GWP100=ifelse(is.na(AR6GWP100),1,AR6GWP100)) %>% 
  mutate(value=value*AR6GWP100) %>% 
  mutate(value=value*1000)

data_primap <- data_primap %>% 
  mutate(country=countrycode(area,"iso3c","country.name")) %>% 
  select(iso=area,country,year,gas,value) %>% 
  mutate(dataset="PRIMAP CR v2.5.1") %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 Fossil",gas)) %>% 
  mutate(gas=ifelse(gas=="FGASES (AR6GWP100)","F-gases",gas))


data_countries <- rbind(data_countries,data_primap)


load(url('https://github.com/lambwf/Codebase/raw/main/data/data_crfs_2023.RData'))

data_crfs <- left_join(data_crfs,gwps %>% select(gas=Species,AR6GWP100))
data_crfs <- data_crfs %>% 
  mutate(value=as.numeric(value)) %>% 
  mutate(AR6GWP100=ifelse(is.na(AR6GWP100),1,AR6GWP100)) %>% 
  mutate(value=value*AR6GWP100) %>% 
  mutate(value=value*1000)

data_crfs <- data_crfs %>% 
  mutate(gas=ifelse(!gas %in% c("CO2","CO2 LULUCF","CH4","N2O"),"F-gases",gas)) %>% 
  group_by(across(c(-value,-AR6GWP100))) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  mutate(year=as.numeric(year)) %>% 
  mutate(gas=ifelse(gas=="CO2","CO2 Fossil",gas)) %>% 
  mutate(dataset="CRFs_2023") %>% 
  ungroup() %>% 
  select(iso,country,year,gas,value,dataset)


data_countries <- rbind(data_countries,data_crfs)

data_countries <- rbind(data_countries,
                        data_lulucf %>%
                          select(iso,country,year,gas,value) %>%
                          mutate(dataset="Grassi et al.") %>%
                          mutate(iso=ifelse(iso=="EUR","EU27",iso)) %>%
                          filter(year<=2021))

# data_countries <- left_join(data_countries,cc_G20 %>% 
#                               add_row(iso="FRA",G20="1") %>% 
#                               add_row(iso="DEU",G20="1") %>% 
#                               add_row(iso="ITA",G20="1") %>% 
#                               add_row(iso="ZAF",G20="1"),by="iso")

# data_countries <- data_countries %>% 
#   filter(G20==1) %>% 
#   select(-G20)

names <- data_countries %>% 
  ungroup() %>% 
  select(iso) %>% 
  distinct() %>% 
  arrange(iso) %>% 
  mutate(country=countrycode(iso,"iso3c","country.name")) %>% 
  mutate(country=ifelse(iso=="AIR","Intl. Aviation",country)) %>% 
  mutate(country=ifelse(iso=="SEA","Intl. Shipping",country)) %>% 
  mutate(country=ifelse(iso=="EU27","European Union",country))


data_countries <- left_join(data_countries %>% ungroup() %>% select(-country),names,by="iso") %>% 
  filter(!is.na(country)) %>% 
  select(iso,country,year,gas,dataset,value) %>% 
  arrange(iso,country,year,gas,dataset)

data_countries <- spread(data_countries,year,value)

addWorksheet(wb,"data_comparison")
writeData(wb, sheet = "data_comparison", data_countries, colNames = T, rowNames = F)


```

```{r figure_high_emitters,fig.height=8,fig.width=10,fig.path="results/",dev=c('png','pdf')}

high_emitters <- data_ghg %>% 
  filter(year==2023) %>% 
  filter(!iso %in% c("WLD","G20","G7","AU55")) %>% 
  group_by(country,iso) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  ungroup() %>%
  arrange(desc(value)) %>%
  mutate(rank=1) %>% 
  mutate(rank=cumsum(rank)) %>% 
  head(6) %>%  
  select(iso,rank)

data_countries <- left_join(data_ghg,high_emitters) %>% 
  filter(!is.na(rank))

data_countries <- data_countries %>% 
  filter(year>=1990) %>% 
  group_by(iso,country,rank,sector_lv1,sector_lv2,sector_lv2_order,sector_lv2_colours,sector_lv2_icons,year) %>%
  summarise(value=sum(value,na.rm=TRUE)/1e6)


#data_countries$sector_lv2 <- fct_relevel(data_countries$sector_lv2,"AFOLU: LULUCF")

labels_colours <- data_countries %>% 
  filter(iso=="CHN") %>% 
  ungroup() %>% 
  filter(year==2021) %>% 
  arrange((sector_lv2)) %>% 
  mutate(position=1) %>% 
  mutate(position=cumsum(position))

data_countries$country = as.factor(data_countries$country)
data_countries$country <- fct_reorder(data_countries$country,data_countries$rank)


data_countries_crfs=left_join(data_crfs,high_emitters) %>%
  filter(!is.na(rank)) %>% 
  filter(gas!="CO2 LULUCF") %>%
  group_by(iso,country,rank,year) %>%
  summarise(value=sum(value,na.rm=T)/1e6)
data_countries_crfs$country <- as.factor(data_countries_crfs$country)
data_countries_crfs$country <- fct_reorder(data_countries_crfs$country,data_countries_crfs$rank)


custom_scales <- data.frame(country=c("China","United States","India","European Union","Russia","Brazil"),
                            x=2023,y=c(15000,10000,5000,5000,5000,5000))
custom_scales$country <- as.factor(custom_scales$country)
custom_scales$country <- fct_relevel(custom_scales$country,"China","United States","India","European Union","Russia","Brazil")

p1 <- data_countries %>% 
  ggplot(aes(x=year,y=value,fill=sector_lv2)) +
  facet_wrap(.~country,scales="free_y",ncol=2) +
  geom_col(color="black",linewidth=0.25) +
  #geom_area(color="#636363") +
  geom_path(data=data_countries_crfs,
           inherit.aes=FALSE,aes(x=year,y=value,group=iso),size=1) +
  geom_blank(data=custom_scales,inherit.aes=FALSE,aes(x=x,y=y)) +
  theme_wl_emissions() +
  #scale_fill_manual(values = labels_colours$sector_lv2_colours) +
  scale_fill_manual(values = colours_9_sectors) +
  ylab("GHG Emissions (MtCO2e/year)") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(size=11),
        panel.grid.major.x = element_blank(),
        strip.background = element_blank(),
        strip.text = element_text(hjust=0,size=11,color="#636363",face="bold"),
        legend.position = "none",
        panel.background = element_blank(),
        panel.spacing = unit(0.5,"cm"))

labels_colours <- labels_colours %>% 
  arrange(desc(sector_lv2_order))

p2 <- labels_colours %>%  ggplot(.,aes(y=rev(sector_lv2_order),label=sector_lv2)) +
  geom_point(aes(x=1.9,fill=as.factor(sector_lv2_order)),
             shape=22,size=4,color='#636363') +
  geom_line(data=data.frame(x=c(1.85,1.95),y=c(0,0)),inherit.aes=FALSE,aes(x=x,y=y),color="black",size=1) + 
  # geom_image(aes(x=2.5+ifelse(sector_lv2=="AFOLU: LULUCF",str_length(sector_lv2)+2,str_length(sector_lv2))/26,image=sector_lv2_icons),by = "height",size=0.06)+ 
  geom_text(hjust=0,aes(x=2),color='#636363',vjust=0.5) +
  geom_text(data=data.frame(label="Inventory (excl. LULUCF)"),hjust=0,inherit.aes=FALSE,aes(x=2,y=0,label=label),color='#636363',vjust=0.5) +
  theme_wl() +
  #scale_fill_manual(values = labels_colours$sector_lv2_colours) +
  scale_fill_manual(values = colours_9_sectors) +
  scale_x_continuous(limits=c(1.8,3.5),expand = c(0,0)) +
  scale_y_continuous(limits=c(-0.5,9.5),expand = c(0,0)) +
  theme(axis.title = element_blank(),
        panel.border = element_blank(),
        legend.position="none",
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_blank(),
        plot.title.position = "plot",
        plot.title = element_text(size=11,colour='#bdbdbd',hjust=1,face = "plain"),
        plot.background = element_blank(),
        plot.margin = unit(c(0,0,0,0),"cm"))

p1 + (plot_spacer() / p2 / plot_spacer() + plot_layout(heights=c(2,3,2))) + plot_layout(widths=c(6,2))


```

```{r data_tables}


high_emitters <- data_ghg %>% 
  filter(year==2023) %>% 
  group_by(country,iso) %>% 
  summarise(value=sum(value,na.rm=TRUE)) %>% 
  ungroup() %>%
  arrange(desc(value)) %>%
  mutate(rank=1) %>% 
  mutate(rank=cumsum(rank)) %>% 
  select(iso,rank)

data_table_countries <- left_join(data_ghg,high_emitters)

data_table_countries <- data_table_countries %>% 
  filter(year>=1990) %>% 
  group_by(iso,country,rank,sector_lv1,sector_lv2,sector_lv2_order,year) %>%
  summarise(value=sum(value,na.rm=TRUE)/1e6)

data_table_countries <- rbind(data_table_countries,data_table_countries %>%
                                filter(sector_lv2!="AFOLU: LULUCF") %>% 
                                group_by(iso,country,rank,year) %>%
                                summarise(value=sum(value)) %>% 
                                mutate(sector_lv2="Total (excl. LULUCF)") %>% 
                                mutate(sector_lv1="Total (excl. LULUCF)") %>% 
                                mutate(sector_lv2_order=9))

data_table_countries$sector_lv2 <- as.factor(data_table_countries$sector_lv2)
data_table_countries$sector_lv2 <- fct_reorder(data_table_countries$sector_lv2,data_table_countries$sector_lv2_order)

data_table_countries <- spread(data_table_countries,year,value) %>% 
  filter(!is.na(rank)) %>% 
  arrange(rank)

data_table_countries <- data_table_countries %>% 
  mutate(change_2022_2023_abs=`2023`-`2022`) %>% 
  mutate(change_2022_2023_rel=change_2022_2023_abs/`2022`)


pct = createStyle(numFmt="0%")
options("openxlsx.numFmt" = "0.00")
addWorksheet(wb,"total_by_country")
writeData(wb, sheet = "total_by_country", data_table_countries, colNames = T, rowNames = F)

addStyle(wb, "total_by_country",style=pct,
         cols=length(data_table_countries),
         rows=2:length(data_table_countries$iso),
         gridExpand=TRUE)



```

``` {r data_tables_indicators}

######## calculate indicators

## Total GHG emissions

data_indicators <- data_ghg %>%
  filter(year %in% c(2022,2023)) %>%
  group_by(iso,country,year) %>%
  summarise(value=sum(value,na.rm=TRUE)/1e6)

data_indicators <- spread(data_indicators,year,value)
data_indicators <- data_indicators %>% 
  rename(ghg_total_2022=`2022`) %>% 
  rename(ghg_total_2023=`2023`)


## Population data from the World Bank

data_wdi_pop<-WDI(country = "all",indicator = "SP.POP.TOTL",start = 1970,end = 2023,extra=TRUE,language = "en") %>%
  select(iso3c, country, year, SP.POP.TOTL) %>%
  filter(!is.na(iso3c))

data_wdi_pop$population <- data_wdi_pop$SP.POP.TOTL
data_wdi_pop$iso <- data_wdi_pop$iso3c
data_wdi_pop<-data_wdi_pop %>% select(-SP.POP.TOTL,-iso3c)

data_indicators <- left_join(data_indicators,data_wdi_pop %>% filter(year==2023) %>% select(iso,population),by = join_by(iso))


## Historic cumulative emissions
# Global Carbon Project CO2 FFI (https://globalcarbonbudget.org/carbonbudget2023/)

data_gcb_co2_ffi <- load_gcb_countries_ffi(read.xlsx("sources/National_Fossil_Carbon_Emissions_2023v1.0.xlsx",sheet=2,startRow = 12))
data_gcb_co2_ffi$iso[grepl("Türkiye",data_gcb_co2_ffi$country)] <- "TUR"

# Global Carbon Project CO2 LUC (https://globalcarbonbudget.org/carbonbudget2023/)

data_gcb_co2_luc <- load_gcb_countries_luc(
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=2),
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=3),
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=4)
)
data_gcb_co2_luc$iso[grepl("Türkiye",data_gcb_co2_luc$country)] <- "TUR"

data_indicators <- left_join(data_indicators,data_gcb_co2_ffi %>% group_by(iso) %>% summarise(co2_ffi_historic=sum(value,na.rm=TRUE)))
data_indicators <- left_join(data_indicators,data_gcb_co2_luc %>% group_by(iso) %>% summarise(co2_luc_historic=sum(mean,na.rm=TRUE)))
data_indicators <- data_indicators %>%
  mutate(co2_historic =sum(co2_ffi_historic,co2_luc_historic,na.rm=T))


### Calculate aggregations

## EU

data_indicators_eu <- left_join(data_indicators,cc_EU,by="iso") %>%
  filter(!is.na(EU)) %>%
  mutate(iso=EU) %>%
  select(-EU)
data_indicators_eu <- gather(data_indicators_eu,var,value,-iso,-country) %>%
  group_by(iso,var) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(country="European Union") %>% 
  mutate(iso="EU27")
data_indicators <- rbind(data_indicators %>% filter(iso!="EU27"),spread(data_indicators_eu,var,value))


## African Union

data_indicators_au <- left_join(data_indicators,cc_AU,by="iso") %>%
  filter(!is.na(AU)) %>%
  mutate(iso=AU) %>%
  select(-AU)
data_indicators_au <- gather(data_indicators_au,var,value,-iso,-country) %>%
  group_by(iso,var) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(country="African Union") %>% 
  mutate(iso="AU55")
data_indicators <- rbind(data_indicators %>% filter(iso!="AU55"),spread(data_indicators_au,var,value))


## Least Developed Countries

cc_LDC <- read.csv("https://raw.githubusercontent.com/openclimatedata/countrygroups/refs/heads/main/data/ldc.csv") %>% 
  select(iso=Code) %>% 
  mutate(LDC=1)

data_indicators_ldc <- left_join(data_indicators,cc_LDC,by="iso") %>%
  filter(!is.na(LDC)) %>%
  mutate(iso="LDC") %>%
  select(-LDC)
data_indicators_ldc <- gather(data_indicators_ldc,var,value,-iso,-country) %>%
  group_by(iso,var) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(country="Least Developed Countries")
data_indicators <- rbind(data_indicators,spread(data_indicators_ldc,var,value))


## G20 (but without AU)

data_indicators_g20 <- left_join(data_indicators,cc_G20,by="iso") %>%
  filter(!is.na(G20)) %>%
  mutate(iso="G20") %>%
  select(-G20)
data_indicators_g20 <- gather(data_indicators_g20,var,value,-iso,-country) %>%
  group_by(iso,var) %>%
  summarise(value=sum(value,na.rm=TRUE)) %>%
  mutate(country="G20")
data_indicators <- rbind(data_indicators %>% filter(iso!="G20"),spread(data_indicators_g20,var,value))


#### Calculate indicators and tidy up

data_indicators <- data_indicators %>% 
  mutate(change_abs=ghg_total_2023-ghg_total_2022) %>% 
  mutate(change_rel=change_abs/ghg_total_2022) %>% 
  mutate(change_rel=round(change_rel*100,1)) %>% 
  mutate(change_rel=ifelse(change_rel>0,paste0("+",change_rel),paste0(change_rel)))

data_indicators <- data_indicators %>%
  mutate(ghg_per_capita=ghg_total_2023/population*1e6) %>% 
  mutate(ghg_per_capita=signif(ghg_per_capita,2))

data_ghg_total <- data_ghg %>% 
  filter(iso=="WLD") %>% 
  filter(sector_lv2!="AFOLU: LULUCF") %>% 
  filter(year==2023) %>% 
  group_by(iso) %>% 
  summarise(value=sum(value,na.rm=TRUE))

data_indicators <- data_indicators %>% 
  mutate(ghg_total_2023_global = sum(data_ghg_total$value)/1e6) %>% 
  mutate(ghg_fraction=ghg_total_2023/ghg_total_2023_global) %>% 
  mutate(ghg_fraction=round(ghg_fraction*100,0)) %>% 
  mutate(ghg_total=signif(ghg_total_2023,3)) %>% 
  mutate(ghg_stat=paste0(ghg_total," (",ghg_fraction,")"))

data_historic_total <- sum(data_gcb_co2_ffi$value[data_gcb_co2_ffi$country=="World"],na.rm=TRUE) +
  sum(data_gcb_co2_luc$mean[data_gcb_co2_luc$country=="Global"],na.rm=TRUE)

data_indicators <- data_indicators %>% 
  mutate(co2_historic_total = data_historic_total) %>% 
  mutate(co2_historic_fraction = co2_historic/co2_historic_total) %>%  
  mutate(co2_historic_fraction=round(co2_historic_fraction*100,0)) %>% 
  mutate(co2_historic = signif(co2_historic,3)) %>% 
  mutate(co2_historic_stat = paste0(co2_historic," (",co2_historic_fraction,")"))



## label indicators

data_indicators_table <- data_indicators %>% 
  select(iso,country,ghg_stat,change_rel,ghg_per_capita,co2_historic_stat) 

data_indicators_table <- data_indicators_table %>%
  set_variable_labels(ghg_stat="MtCO2e (% of total)",
                      change_rel="%",
                      ghg_per_capita="tCO2e/person",
                      co2_historic_stat="GtCO2 (% of total)")


data_indicators_table <- data_indicators_table %>%
  rename(`Total GHG emissions in 2023`=ghg_stat) %>% 
  rename(`Change in total GHG emissions, 2022-2023`=change_rel) %>% 
  rename(`Per capita GHG emissions in 2022`=ghg_per_capita) %>% 
  rename(`Historic CO2 emissions, 1850-2023`=co2_historic_stat)


data_indicators_table <- data_indicators_table %>% 
  filter(iso %in% c("CHN","USA","IND","EU27","RUS","BRA","AU55","LDC","G20"))

data_indicators_table$iso <- as.factor(data_indicators_table$iso)
data_indicators_table$iso <- fct_relevel(data_indicators_table$iso,"CHN","USA","IND","EU27","RUS","BRA","AU55","LDC","G20")
data_indicators_table <- data_indicators_table %>% 
  arrange(iso)


addWorksheet(wb,"table_2")
writeData(wb, sheet = "table_2", data_indicators_table, colNames = T, rowNames = F)

addWorksheet(wb,"aggregations")
writeData(wb, sheet = "aggregations", cc_aggregates, colNames = T, rowNames = F)




saveWorkbook(wb,paste0("results/UNEP-Gap-Report-2024-Chapter-2-Data-Countries.xlsx"),overwrite=T)




# 
# data_indicators <- gather_with_labels(data_indicators,c("ghg_total","change_rel","ghg_per_capita","co2_historic"))
# 
# data_indicators <- data_indicators %>%
#   rename(units=label) %>%
#   mutate(label=ifelse(var=="ghg_total","Total GHG emissions in 2023:",NA)) %>%
#   mutate(label=ifelse(var=="ghg_per_capita","Per capita GHG emissions in 2022:",label)) %>%
#   mutate(label=ifelse(var=="change_rel","Change in total GHG emissions 2022-2023:",label)) %>%
#   mutate(label=ifelse(var=="co2_historic","Historic CO2 emissions 1850-2023:",label))
# 
# data_indicators <- data_indicators %>%
#   mutate(value=ifelse(var=="ghg_total",signif(value,3),value)) %>%
#   mutate(value=ifelse(var=="ghg_per_capita",signif(value,3),value)) %>%
#   mutate(value=ifelse(var=="co2_cons_per_capita",signif(value,3),value)) %>%
#   mutate(value=ifelse(var=="co2_historic",signif(value,3),value))
# 
# data_indicators <- data_indicators %>%
#   mutate(value=paste0(value," ",units))
# 



```

``` {r small_things}

### intl transport

data_airsea <- data_ghg %>% 
  filter(iso %in% c("AIR","SEA")) %>% 
  group_by(year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## top 3 deforestation countries

data_tropical <- data_gcb_co2_luc %>% 
  filter(iso %in% c("BRA","IDN","COD")) %>% 
  group_by(year) %>% 
  summarise(value=sum(mean))

data_tropical <- left_join(data_tropical,data_gcb_co2_luc %>% filter(country=="Global") %>% select(year,global_total=mean),by="year")
data_tropical <- data_tropical %>% 
  mutate(fraction=value/global_total)


## global per capita ghg emissions

data_percap <- data_ghg %>% 
  filter(iso=="WLD") %>% 
  filter(sector_lv2!="AFOLU: LULUCF") %>% 
  group_by(year) %>% 
  summarise(value=sum(value,na.rm=TRUE))

data_percap <- left_join(data_percap,data_wdi_pop %>% filter(country=="World") %>% select(year,population))
data_percap <- data_percap %>% 
  mutate(value_pc=value/population)


## share of top 6 in global emissions

data_top <- data_ghg %>% 
  filter(iso %in% c("CHN","USA","EU27","IND","RUS","BRA")) %>% 
  group_by(year) %>% 
  summarise(value=sum(value))
data_top <- left_join(data_top,data_ghg %>% filter(iso=="WLD") %>% group_by(year) %>% summarise(value_world=sum(value)))
data_top <- data_top %>% 
  mutate(fraction=value/value_world)

## population share of top emitters
data_pop <- data_indicators %>% 
  filter(iso %in% c("CHN","USA","EU27","IND","RUS","BRA","LDC","AU55")) %>% 
  select(iso,country,population) %>% 
  mutate(year=2023)
data_pop <- left_join(data_pop,data_wdi_pop %>% filter(country=="World") %>% select(year,pop_world=population))
data_pop <- data_pop %>% 
  mutate(fraction=population/pop_world) %>% 
  mutate(fraction=fraction*100) %>% 
  mutate(fraction=round(fraction,0))



## share of G20 incl. AU55 in global emissions
data_share <- data_ghg %>% 
  filter(iso %in% c("AUS","ARG","BRA","CAN","CHN","EU27","IND","IDN","JPN","MEX","RUS","SAU","KOR","TUR","GBR","USA","ZAF")) %>% 
  group_by(year) %>% 
  summarise(value=sum(value))

data_share <- left_join(data_share,data_ghg %>% filter(iso=="WLD") %>% group_by(year) %>% summarise(value_world=sum(value)))
data_share <- data_share %>% 
  mutate(fraction=value/value_world)


## the growth rates of G20 vs non-G20 countries
data_growth <- data_ghg %>% 
  ungroup() %>% 
  filter(!iso %in% c("WLD","G20","G7","AU55","EU27"))      # remove aggregates

data_growth <- left_join(data_growth,cc_G20,by="iso")
data_growth <- left_join(data_growth,cc_EU,by="iso")

data_growth <- data_growth %>% 
  filter(year %in% c(2022,2023)) %>% 
  mutate(G20=ifelse(!is.na(EU),1,G20)) %>% 
  mutate(G20=ifelse(is.na(G20),0,G20)) %>% 
  group_by(year,G20) %>% 
  summarise(value=sum(value,na.rm=TRUE))

data_growth <- left_join(data_growth,
                         data_ghg %>% 
                           filter(iso=="WLD") %>% 
                           group_by(year) %>% 
                           summarise(global_total=sum(value,na.rm=TRUE)),by="year")

data_growth <- data_growth %>% 
  mutate(ratio=value/global_total) %>% 
  group_by(G20) %>% 
  mutate(change_abs=last(value)-first(value),
         change_rel=change_abs/first(value)) %>% 
  mutate(change_rel=round(change_rel*100,2))


```


### individual country plots

```{r plot_countries,fig.height=4,fig.width=8.5}
country_iso="DEU"
pull_out_year=2023

plot_country <- function(country_iso,data_ghg,data_crfs,data_indicators,pull_out_year) {
  
  data_countries <- data_ghg %>%
    filter(iso==country_iso) %>%
    filter(year>=1990) %>%
    group_by(iso,country,sector_lv2,sector_lv2_colours,sector_lv2_order,sector_lv2_icons,year) %>%
    summarise(value=sum(value,na.rm=TRUE)/1e6)
  
  ### join LULUCF data if EU country (as these are not in Grassi's dataset)
  if (sum(grepl(country_iso,cc_EU$iso))==1) { 
    
    data_crf_lulucf <- data_crfs %>%
      filter(year>=1990) %>% 
      filter(iso==country_iso) %>%
      filter(gas=="CO2 LULUCF") %>%
      mutate(value=value/1e6) %>% 
      select(iso,country,year,value) %>% 
      mutate(sector_lv2="AFOLU: LULUCF") %>% 
      mutate(sector_lv2_colours="#a6d854") %>% 
      mutate(sector_lv2_order=8) %>% 
      mutate(sector_lv2_icons="C:/Users/lamw/ownCloud/Projects/UNEP-Gap-Report-2024/sources/icons/Land use.png")
    
    data_countries <- rbind(data_countries %>% filter(sector_lv2!="AFOLU: LULUCF"),data_crf_lulucf)
    data_countries$sector_lv2 <- fct_reorder(data_countries$sector_lv2,data_countries$sector_lv2_order)
    
  }
  
  ## project missing LULUCF data
  # data_countries_lulucf <- spread(data_countries,year,value) 
  # data_countries_lulucf <- gather(data_countries_lulucf,year,value,`1990`:`2023`) %>% 
  #   filter(sector_lv2=="AFOLU: LULUCF")
  # projection=2023-length(data_countries_lulucf$value[is.na(data_countries_lulucf$value)])
  # data_countries_lulucf <- data_countries_lulucf %>%
  #   mutate(year=as.numeric(year)) %>% 
  #   arrange(year) %>% 
  #   na.locf()
  # data_countries <- rbind(data_countries %>% filter(sector_lv2!="AFOLU: LULUCF"),data_countries_lulucf)
  # data_countries <- data_countries %>% mutate(blarg=ifelse(sector_lv2=="AFOLU: LULUCF" & year>=projection,"0",NA))
  
  
  labels_colours <- data_ghg %>% 
    filter(iso=="CHN") %>% 
    group_by(iso,country,sector_lv2,sector_lv2_colours,sector_lv2_order,sector_lv2_icons,year) %>%
    summarise(value=sum(value,na.rm=TRUE)/1e6)
  
  
  labels_colours <- labels_colours %>% 
    ungroup() %>% 
    filter(year==2021) %>% 
    arrange((sector_lv2)) %>% 
    mutate(position=1) %>% 
    mutate(position=cumsum(position)) %>% 
    select(-value)
  
  labels_colours <- left_join(labels_colours,data_countries %>% 
                                ungroup() %>% 
                                filter(year==pull_out_year) %>% 
                                select(sector_lv2,value),by="sector_lv2")
  
  ## calculate % share in pull out year relative to gross emissions
  
  country_total <- data_countries %>% 
    filter(year==pull_out_year) %>% 
    filter(value>0)
  
  labels_colours <- labels_colours %>% 
    mutate(total=sum(country_total$value)) %>% 
    mutate(share=value/total) %>% 
    mutate(share=round(share*100)) %>%
    mutate(share=ifelse(share<0,NA,share)) %>% 
    mutate(label=paste0(share,"% "))
  
  labels_colours$label <- gsub("NA%"," - ",labels_colours$label)
  
  data_countries_crfs=data_crfs %>%
    filter(year>=1990) %>% 
    filter(iso==country_iso) %>%
    filter(gas!="CO2 LULUCF") %>%
    group_by(iso,country,year) %>%
    summarise(value=sum(value,na.rm=T)/1e6) %>% 
    ungroup() 
  
  data_countries_crfs <- data_countries_crfs %>% 
    arrange(year) %>%
    add_row(year=max(data_countries_crfs$year)+1,value=NA) %>% 
    mutate(iso=na.locf(iso), country=na.locf(country))
  
  is_crf <- ifelse(!is.na(data_countries_crfs$iso[1]),"T","F")
  
  indicator_text <- data_indicators %>% filter(iso==country_iso)
  
  indicator_text = paste0(data_countries$country[1]," released an estimated ",indicator_text$ghg_total[1]," MtCO2e in 2023 (excl. LULUCF), a change of ",indicator_text$change_rel[1]," % compared to the previous year. Per capita GHG emissions were ",indicator_text$ghg_per_capita[1], " tCO2e in 2023. Cumulative CO2 emissions since 1850 were ",indicator_text$co2_historic[1]," GtCO2, or about ",indicator_text$co2_historic_fraction[1], "% of global emissions to date.")
  
  
  
  p1 <- ggplot() +
    geom_col(data=data_countries,color='#252525',linewidth=0.25,aes(x=year,y=value,fill=sector_lv2)) +
    
    {if(is_crf) geom_path(data=data_countries_crfs,
                          inherit.aes=FALSE,
                          aes(x=year,y=value,group=iso,fill=NA),
                          size=0.75,
                          color='#d45087ff')} +
    
    theme_wl_emissions() +
    scale_fill_manual(values = colours_9_sectors) +
    scale_x_continuous(breaks=c(1990,2000,2010,2020)) +
    theme(axis.title = element_blank(),
          legend.position = "none",
          plot.subtitle = element_text(size=11)) +
    labs(title=data_countries$country,
         subtitle=bquote("Greenhouse gas emissions (Mt" *CO[2]* "e/year)"),
         caption=str_wrap(paste0(indicator_text,"\n⌂ EDGAR v9, GCB 2023, UNFCCC, Grassi et al. 2021 ⌂ CC-BY William F. Lamb"),125))
  
  
  p2 <- labels_colours %>%  
    arrange(sector_lv2_order) %>%
    ggplot(.,aes(y=rev(sector_lv2_order))) +
    geom_text(aes(x=1.9,label=label),color='#636363') +
    geom_point(aes(x=2.1,fill=as.factor(rev(sector_lv2_order))),
               shape=22,size=4,color='#252525') +
    
    {if(is_crf) geom_line(data=data.frame(x=c(2.05,2.15),y=c(0,0)),
                          inherit.aes=FALSE,
                          aes(x=x,y=y),
                          color='#d45087ff',size=1)} +
    
    geom_text(hjust=0,aes(x=2.2,label=sector_lv2),color='#636363',vjust=0.5) +
    {if(is_crf) geom_text(data=data.frame(label="Inventory (excl. LULUCF)"),
                          inherit.aes=FALSE,
                          aes(x=2.2,y=0,label=label),
                          color='#636363',vjust=0.5,hjust=0)} +
    theme_wl() +
    scale_fill_manual(values = rev(colours_9_sectors)) +
    scale_x_continuous(limits=c(1.8,3.5),expand = c(0,0)) +
    scale_y_continuous(limits=c(-0.5,9.5),expand = c(0,0)) +
    theme(axis.title = element_blank(),
          panel.border = element_blank(),
          legend.position="none",
          axis.text.x = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.major = element_blank(),
          plot.title.position = "plot",
          plot.title = element_text(size=11,colour='#bdbdbd',hjust=1,face = "plain"),
          plot.background = element_blank(),
          plot.margin = unit(c(0,0,0,0),"cm"),
          axis.text = element_text(size=10.5),
          plot.subtitle = element_text(size=11)) +
    labs(subtitle=paste0("Sectors & shares of gross\nemissions in ",pull_out_year))
  
  
  
  # p <-  wrap_elements(p1) + plot_spacer() + 
  #   wrap_elements(plot_spacer() / p2 / plot_spacer() + plot_layout(heights=c(0.5,10,ifelse(is_crf=="T",1.75,1))) & theme(plot.background=element_blank())) + 
  #   plot_layout(widths=c(6,-0.25,3.8))
  # 
  
  p <- p1 + theme(plot.subtitle = element_text(margin = margin(t = 4))) + plot_spacer() + p2 +
    plot_layout(widths=c(6,0.15,3.5))
  p
  
  return(p)
  
}

```

```{r country_test, fig.width=9,fig.height=4,echo=FALSE,warning=FALSE}

# 
plot_country("USA",data_ghg,data_crfs,data_indicators,2023)
plot_country("BRA",data_ghg,data_crfs,data_indicators,2023)
plot_country("DEU",data_ghg,data_crfs,data_indicators,2023)
plot_country("AIA",data_ghg,data_crfs,data_indicators,2023)
plot_country("LBR",data_ghg,data_crfs,data_indicators,2023)
plot_country("IRL",data_ghg,data_crfs,data_indicators,2023)
plot_country("SWE",data_ghg,data_crfs,data_indicators,2023)

# ggsave(plot_country("BRA",data_ghg,data_indicators,"yes"),filename = "test.png",path = "results/",device = "png",height = 4,width=8.5,dpi=300)

```



```{r plots, fig.width=9,fig.height=4,echo=FALSE}

## only plot countries with EDGAR data and pop data 

countries <- data_ghg %>%
  ungroup() %>%
  filter(year==2020) %>%
  filter(sector_lv2!="AFOLU: LULUCF") %>%
  select(iso,country) %>%
  distinct()

countries <- left_join(countries,data_wdi_pop %>% filter(year==2020) %>% select(iso,population))
#countries <- left_join(countries,data_gcb_co2_ffi %>% filter(year==2020) %>% select(iso,gcb=value))
countries <- countries %>%
  mutate(population=ifelse(iso=="AIR",1,population)) %>%
  mutate(population=ifelse(iso=="SEA",1,population)) %>%
  mutate(population=ifelse(iso=="EU27",1,population)) %>%
  filter(population>=350000) %>% 
  filter(!is.na(population)) %>%
  select(iso,country)


for (i in 1:length(countries$iso)) {

  plot <- plot_country(countries$iso[i],data_ghg,data_crfs,data_indicators,2023)

  ggsave(plot,filename = paste0(countries$country[i],".png"),path = "results/countries/",device = "png",height = 4,width=8.5,dpi=300)
  ggsave(plot,filename = paste0(countries$country[i],".pdf"),path = "results/countries/",device = cairo_pdf,height = 4,width=8.5)
  ggsave(plot,filename = paste0(countries$country[i],".svg"),path = "results/countries/",device = 'svg',height = 4,width=8.5)


}


# blarg <- left_join(data_ghg,cc_AU,by="iso") %>%
#   filter(AU==1) %>%
#   filter(year>=1990) %>%
#   group_by(sector_lv2,sector_lv2_colours,sector_lv2_order,sector_lv2_icons,year) %>%
#   summarise(value=sum(value,na.rm=TRUE)) %>%
#   mutate(iso="AU55") %>%
#   mutate(country="African Union")
# 
# #plot_country("AU55",blarg,data_crfs,data_indicators,2023)
# 
# ggsave(p,filename = "African Union.png",path = "results/countries",device = "png",height = 4,width=8.5,dpi=300)
# ggsave(p,filename = "African Union.pdf",path = "results/countries/",device = cairo_pdf,height = 4,width=8.5)
# ggsave(p,filename = "African Union.svg",path = "results/countries",device = "svg",height = 4,width=8.5)


```




``` {r save}
# 
# data_output <- data_ghg %>% 
#   filter(year==2022) %>% 
#   group_by(iso,subsector) %>% 
#   summarise(value=sum(value,na.rm=T)/1e6)
# 
# data_output <- rbind(data_output,data_lulucf %>% 
#                        filter(year==2020) %>% 
#                        mutate(subsector="AFOLU: Land use") %>% 
#                        filter(!is.na(iso)) %>% 
#                        mutate(value=value/1e6) %>% 
#                        select(iso,subsector,value))
# 
# data_output <- data_output %>% 
#   group_by(iso) %>% 
#   mutate(`Total GHG emissions (MtCO2e)`=sum(value,na.rm=TRUE)) %>% 
#   mutate(ratio=value/`Total GHG emissions (MtCO2e)`*100) %>% 
#   mutate(ratio=round(ratio,2))
# 
# data_output$subsector <- as.factor(data_output$subsector)
# data_output$subsector <- fct_relevel(data_output$subsector,"Waste & Other","AFOLU: Land use","AFOLU: Agriculture","Industrial processes","Energy: Fuel production","Energy: Buildings","Energy: Transport","Energy: Industry","Energy: Power")
# data_output$subsector <- fct_rev(data_output$subsector)
# 
# data_output <- data_output %>% 
#   mutate(country=countrycode(iso,"iso3c","country.name")) %>% 
#   mutate(country=ifelse(iso=="ANT","Netherlands Antilles",country)) %>% 
#   mutate(country=ifelse(iso=="SCG","Serbia and Montenegro",country)) %>% 
#   mutate(country=ifelse(iso=="AIR","Intl. Aviation",country)) %>% 
#   mutate(country=ifelse(iso=="SEA","Intl. Shipping",country)) %>% 
#   mutate(country=ifelse(iso=="EU27","European Union",country)) %>% 
#   select(country,iso,everything())
# 
# 
# wb <- createWorkbook()
# addWorksheet(wb,"sector_emissions_MtCO2e_2022")
# addWorksheet(wb,"sector_ratios_%_2022")
# 
# writeData(wb, sheet = "sector_emissions_MtCO2e_2022",spread(data_output %>% select(-ratio),subsector,value),colNames = T, rowNames = F)
# writeData(wb, sheet = "sector_ratios_%_2022",spread(data_output %>% select(-value),subsector,ratio),colNames = T, rowNames = F)
# 
# saveWorkbook(wb,paste0("results/UNEP-Gap-Report-2024-Country-Sector-Emissions.xlsx"),overwrite=T)
# 
# 
# 
# metadata <- labelled::generate_dictionary(data_indicators) %>% 
#   select(variable,units=label)

``` 



``` {r old}

# p1 <- data_countries %>% ggplot(aes(x=year,y=value,fill=subsector)) +
#     geom_area(color="#636363") +
#     theme_wl() +
#     scale_fill_manual(values = my_colours$colour) +
#     ylab("GHG Emissions (MtCO2e/year)") +
#     theme(axis.title.x = element_blank(),
#           panel.grid.major.x = element_blank(),
#           panel.border = element_blank(),
#           axis.line.x=element_line(colour='#636363'),
#           axis.line.y=element_line(colour='#636363'),
#           legend.position = "none",
#           panel.background = element_blank(),plot.margin = unit(c(0,0,0,0.5),"cm"),
#           plot.title.position = "plot",
#           plot.subtitle=element_text(margin=margin(0,0,10,0)),
#           plot.tag = element_text(size=11,colour='#bdbdbd',hjust=1)) +
#     labs(title=name)
# 
#   if (annotations=="yes") {
#     p1 <- p1 + labs(subtitle="Emissions trends and indicators")
#   }
# 
# 
#   p2 <-  labels %>%  ggplot(.,aes(y=position,label=subsector)) +
#     geom_point(aes(x=1.9,fill=subsector),
#                shape=22,size=3,color='white') +
#     geom_image(aes(x=2.4+str_length(subsector)/24,image=icons),by = "height",size=0.085)+
#     geom_text(hjust=0,aes(x=2),color='#636363',vjust=0.5) +
#     theme_wl() +
#     scale_fill_manual(values = c(labels$colour)) +
#     scale_x_continuous(limits=c(1.9,3.5)) +
#     scale_y_continuous(limits=c(0.5,9.5),expand = c(0,0)) +
#     theme(axis.title = element_blank(),
#           panel.border = element_blank(),
#           legend.position="none",
#           axis.text.x = element_blank(),
#           axis.text.y = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.major = element_blank(),
#           plot.title.position = "plot",
#           plot.title = element_text(size=11,colour='#bdbdbd',hjust=1,face = "plain"),
#           plot.background = element_blank(),
#           plot.margin = unit(c(0,0,0,0),"cm"))
# 
#   if (annotations=="yes") {
#     p2 <- p2 + labs(title="Sources: EDGAR | GCB | Grassi et al.")
#   }
# 
# 
#   ## indicators plot
# 
#   p3 <- data_indicators %>%
#     mutate(facet=ifelse(grepl("per_capita",var),"per_capita","totals")) %>%
#     ungroup() %>%
#     filter(iso==country_iso) %>%
#     #add_row(var="empty",label="",value="") %>%
#     ggplot(.,aes(x=1,y=label,label=value)) +
#     geom_text(size=10*(0.36),hjust=0,vjust=0.5,color='#636363')  +
#     facet_wrap(.~facet,scales="free") +
#     #scale_y_discrete(labels = function(x) str_wrap(x, width = 20))+
#     scale_x_continuous(limits=c(1,3)) +
#     theme_wl()+
#     theme(axis.title = element_blank(),
#           axis.ticks = element_blank(),
#           panel.background = element_blank(),
#           panel.border = element_blank(),
#           panel.grid = element_blank(),
#           axis.text.x = element_blank(),
#           axis.text.y = element_text(size=10),
#           plot.caption = element_text(size=11,colour='#bdbdbd',hjust=1),strip.background = element_blank(),strip.text = element_blank())
# 
# 
#   p <- plot_spacer() / (p1 + plot_spacer() + p2 + plot_layout(widths=c(4,0.2,2.2))) / plot_spacer() / wrap_elements(p3) + plot_layout(heights=c(0.1,6,-0.9,2))  +
#     plot_annotation(theme = theme_wl() +
#                       theme(plot.background = element_rect(fill = NA, colour = '#636363', size = 0.5)))
#   p


```


