---
title: "UNEP-Gap-Report-2024-Global-Totals"
author: "William F. Lamb"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

rm(list = ls())

library(tidyverse)
library(openxlsx)
library(countrycode)
library(ggrepel)
library(patchwork)
library(zoo)
library(RColorBrewer)
library(WDI)
library(labelled)
library(grid)
library(ggimage)

source("https://raw.githubusercontent.com/lambwf/Codebase/main/figure_style.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/reshape_with_labels.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/locate_shares.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_gcb_countries_v2023.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_edgar_v9.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/growth_rate.R")

```


## Load data

```{r load_data}

#### Load and organise EDGAR data

# Load EDGAR data (https://edgar.jrc.ec.europa.eu/dataset_ghg80)

edgar_co2  <- read.xlsx("sources/not public/EDGAR_2024_CO2_1970_2023_v2.xlsx",sheet=2,startRow=9)
edgar_ch4  <- read.xlsx("sources/not public/EDGAR_2024_CH4_1970_2023_v2.xlsx",sheet=2,startRow = 9)
edgar_n2o  <- read.xlsx("sources/not public/EDGAR_2024_N2O_1970_2023_v2.xlsx",sheet=2,startRow = 9)
edgar_fgas <- read.xlsx("sources/not public/EDGAR_2024_F-gases_1970_2023_v2.xlsx",sheet=2,startRow = 9)
data_ghg   <- load_edgar(edgar_co2,edgar_ch4,edgar_n2o,edgar_fgas)


# Remove biogenic CO2 as these emissions are normally accounted in equilibrium with removals

data_ghg <- data_ghg %>% filter(gas!="CO2bio")


# Load global warming potentials (GWPs) to calculate CO2e for each gas

gwps <- read.csv("https://raw.githubusercontent.com/openclimatedata/globalwarmingpotentials/main/globalwarmingpotentials.csv",skip = 10)
gwps <- gwps %>% select(gas=Species,gwp100=AR6GWP100)


# Join GWPs

data_ghg$gas <- gsub("-","",data_ghg$gas)
data_ghg <- left_join(data_ghg,gwps) %>% 
  mutate(gwp100=ifelse(gas=="CO2",1,gwp100))


# Check that all gwps joined

check <- data_ghg %>% filter(is.na(gwp100))
check <- data_ghg %>% select(gas,gwp100) %>% distinct()


# Calculate CO2e for each gas

data_ghg <- data_ghg %>% mutate(value_gwp=value*gwp100)


# Create list of individual f-gases to merge these into a single gas variable

list_fgases <- data_ghg %>% 
  select(gas) %>% 
  distinct() %>% 
  mutate(group=ifelse(gas=="CO2","CO2 Fossil",NA)) %>% 
  mutate(group=ifelse(gas=="CH4","CH4",group)) %>% 
  mutate(group=ifelse(gas=="N2O","N2O",group)) %>% 
  mutate(group=ifelse(is.na(group),"F-gases",group))


# Group f-gases into a single variable

data_ghg <- left_join(data_ghg,list_fgases,by="gas")
data_ghg <- data_ghg %>% 
  mutate(gas=group) %>% 
  group_by(iso,country,code,code_description,gas,year) %>% 
  summarise(value=sum(value_gwp,na.rm=TRUE))


# Convert Gg to tons

data_ghg$value = data_ghg$value*1000


# Sum up emissions to sector and year

data_ghg <- data_ghg %>% 
  group_by(code,code_description,gas,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


# Check global totals

check <- data_ghg %>% filter(year==2023) %>% group_by(gas) %>% summarise(value=sum(value,na.rm=T))
sum(check$value)


#### Join additional global data

# Load Global Carbon Budget (GCB) CO2 land use change (LUC) emissions (https://globalcarbonbudget.org/carbonbudget2023/)

data_gcb_co2_luc <- load_gcb_countries_luc(
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=2),
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=3),
  readxl::read_xlsx('sources/National_LandUseChange_Carbon_Emissions_2023v1.0.xlsx',range="A8:GT182",sheet=4))

data_gcb_co2_luc <- data_gcb_co2_luc %>% 
  filter(year>=1970) %>% 
  filter(country=="Global") %>% 
  select(year,value=mean) %>% 
  mutate(year=as.numeric(year)) %>% 
  mutate(value=value*1e9)


# Add the GCB projection for 2023 (https://essd.copernicus.org/articles/15/5301/2023/) and join

data_gcb_co2_luc <- data_gcb_co2_luc %>% 
  add_row(year=2023,value=1.1*(44/12)*1e9)

data_gcb_co2_luc <- data_gcb_co2_luc %>% 
  mutate(code="3B") %>% 
  mutate(code_description="Land use change") %>% 
  mutate(gas="CO2 LULUCF")

data_ghg <- rbind(data_ghg,data_gcb_co2_luc)


# Add cement carbonation from GCB (https://globalcarbonbudget.org/carbonbudget2023/)

data_gcb_co2_cc <- read.xlsx('sources/Global_Carbon_Budget_2023v1.1.xlsx',sheet=2,startRow = 22,cols=c(1,7))
data_gcb_co2_cc <- data_gcb_co2_cc %>%
  rename(year=Year,value=cement.carbonation.sink) %>%
  mutate(value=-(value*(44/12)*1e9)) %>%
  mutate(code="2.A.1.X") %>%
  mutate(code_description="Cement carbonation") %>%
  mutate(gas="CO2 Fossil")

# data_ghg <- rbind(data_ghg,data_gcb_co2_cc)


# Load global fire emissions (GFED) CH4 data (https://www.geo.vu.nl/~gwerf/GFED/GFED4/tables/GFED4.1s_CH4.txt)
# Following GCB convention, only use global tropical fires and SE Asia peat fires

data_gfed_ch4 <- read.xlsx("sources/GFED4.1s_2024.xlsx",sheet="GFED_CH4",rows = c(14,105,122))
data_gfed_ch4 <- gather(data_gfed_ch4,year,value,`1997`:`2023`)
data_gfed_ch4 <- data_gfed_ch4 %>%
  group_by(year) %>%
  summarise(value=sum(value))

data_gfed_ch4 <- data_gfed_ch4 %>%
  mutate(var="CH4") %>%
  select(year,var,value) %>%
  mutate(value=value*1E10) %>% #1e10 grams to grams
  mutate(value=value/1e6) %>%
  mutate(value=value/1e6) %>%
  mutate(source="GFED v4.1*") %>%
  mutate(units="MtCH4") %>%
  select(year,value,source,var,units)


# Load global fire emissions (GFED) N2O data (https://www.geo.vu.nl/~gwerf/GFED/GFED4/tables/GFED4.1s_N2O.txt)
# Following GCB convention, only use global tropical fires and SE Asia peat fires

data_gfed_n2o <- read.xlsx("sources/GFED4.1s_2024.xlsx",sheet="GFED_N2O",rows = c(14,105,122))
data_gfed_n2o <- gather(data_gfed_n2o,year,value,`1997`:`2023`)
data_gfed_n2o <- data_gfed_n2o %>%
  group_by(year) %>%
  summarise(value=sum(value))

data_gfed_n2o <- data_gfed_n2o %>%
  mutate(var="N2O") %>%
  mutate(value=value*1E9) %>% #1e9 grams to grams
  mutate(value=value/1e6) %>%
  mutate(value=value/1e6) %>%
  mutate(source="GFED v4.1*") %>%
  mutate(units="MtN2O") %>%
  select(year,value,source,var,units)


# Extend GFED to before 1997 using CMIP6 input data 
# (https://github.com/openclimatedata/global-biomass-burning-emissions/blob/main/data/gbbe-extended.csv)
# (Not possible because CMIP6 doesn't dissaggregate by source or region)

# data_gfed_extension <- read.csv("https://raw.githubusercontent.com/openclimatedata/global-biomass-burning-emissions/main/data/gbbe-extended.csv")
# data_gfed_extension <- data_gfed_extension %>% 
#   select(year=Year,CH4,N2O) %>% 
#   mutate(year=as.character(year))
# 
# data_gfed_ch4 <- full_join(data_gfed_ch4,data_gfed_extension %>% select(year,CH4))
# data_gfed_ch4 <- data_gfed_ch4 %>% 
#   mutate(source=na.locf(source)) %>% 
#   mutate(var=na.locf(var)) %>% 
#   mutate(units=na.locf(units)) %>% 
#   arrange(year) %>% 
#   mutate(value=ifelse(year<1997,CH4,value)) %>% 
#   select(-CH4)
# 
# data_gfed_n2o <- full_join(data_gfed_n2o,data_gfed_extension %>% select(year,N2O))
# data_gfed_n2o <- data_gfed_n2o %>% 
#   mutate(source=na.locf(source)) %>% 
#   mutate(var=na.locf(var)) %>% 
#   mutate(units=na.locf(units)) %>% 
#   arrange(year) %>% 
#   mutate(value=ifelse(year<1997,N2O,value)) %>% 
#   select(-N2O)
 

# Join GFED CH4 and N2O to data frame

data_gfed <- rbind(data_gfed_ch4,data_gfed_n2o)
data_gfed <- left_join(data_gfed,gwps,by=c("var"="gas"))
data_gfed <- data_gfed %>%
  filter(year>=1970) %>%
  mutate(value=value*gwp100) %>%
  mutate(value=value*1e6)
data_gfed <- data_gfed %>%
  select(year,value,gas=var) %>%
  mutate(code="3X") %>%
  mutate(code_description="Fires") %>%
  mutate(year=as.numeric(year))

# data_ghg <- rbind(data_ghg,data_gfed)


#### Aggregate sectors and set factor levels

# Aggregate sectors based on own excel file

write.xlsx(data_ghg %>% ungroup() %>% select(code,code_description) %>% distinct() %>% arrange(code),"cc_sectors.xlsx")
data_ghg <- left_join(data_ghg,read.xlsx("sources/cc_sectors.xlsx"),by=join_by(code, code_description))


# Set factor order based on own excel file

data_ghg$gas <- as.factor(data_ghg$gas)
data_ghg$gas <- fct_relevel(data_ghg$gas,"CO2 Fossil","CO2 LULUCF","CH4","N2O","F-gases")

data_ghg$sector_lv1 <- as.factor(data_ghg$sector_lv1)
data_ghg$sector_lv1 <- fct_reorder(data_ghg$sector_lv1,data_ghg$sector_lv1_order)

data_ghg$sector_lv2 <- as.factor(data_ghg$sector_lv2)
data_ghg$sector_lv2 <- fct_reorder(data_ghg$sector_lv2,data_ghg$sector_lv2_order)

data_ghg$sector_lv3 <- as.factor(data_ghg$sector_lv3)
data_ghg$sector_lv3 <- fct_reorder(data_ghg$sector_lv3,data_ghg$sector_lv3_order)


```

## Plot a figure showing global emissions by gas

``` {r figure_global_gases,fig.width=8,fig.height=4, fig.path="results/",dev=c('png','pdf','svg')}

# Calculate total emissions by gas and year

plot_ghgs <- data_ghg %>% 
  filter(year>=1990) %>%
  group_by(gas,year) %>%
  summarise(value=sum(value,na.rm=TRUE)/1e9)


# Calculate total emissions by year

plot_ghgs_totals <- plot_ghgs %>% 
  group_by(year) %>% 
  summarise(totals=sum(value))


# Make variable to display vertical lines and totals each decade

line_data <- data.frame(x=c(1990,1990,2000,2000,2010,2010,2020,2020,2023,2023),y=c(0,60))


# Plot

plot_ghgs %>% ggplot(aes(x=year,y=value,fill=fct_rev(gas))) +
  
  geom_area(color="#636363") +
  geom_line(inherit.aes = FALSE,
            data=line_data,aes(x=x,y=y,group=x),
            alpha=0.3,linetype="dashed") +
  geom_text(inherit.aes = FALSE,
            data=plot_ghgs_totals %>% filter(year %in% c(1990,2000,2010,2020,2023)),
            aes(x=year,y=63,label=paste(signif(totals,3))),
            size=3.5,colour="#252525") +
  
  #ylab("GHG Emissions (GtCO2e/year)") +
  scale_fill_manual(values=c("#e78ac3","#fc8d62","#8da0cb","#66c2a5","#a6d854")) +
  scale_x_continuous(breaks=c(1990,2000,2010,2020,2023)) +
  
  theme_wl() +
  theme(axis.title.x = element_blank(),
        axis.line.x=element_line(colour='#636363'),
        axis.line.y=element_line(colour='#636363'),
        panel.grid.major.x = element_blank(),
        panel.border = element_blank(),
        legend.position = "right",
        legend.title = element_blank()) +
  labs(title="Total net anthropogenic greenhouse gas emissions from 1990-2023",
       subtitle=bquote("Gt" ~CO[2]~ "/year"))


```

## Tables of total emissions by gas

```{r table_totals}


# Compile and join national GHG inventory LULUCF data, for comparison with bookkeeping data

data_grassi <- read.xlsx('sources/not public/LULUCF NGHGI data for UNEP 2024.xlsx',startRow = 3) %>% 
  rename(category=LAND.CATEGORY,country=UNFCCC.country,iso=country.code)
data_grassi <- gather(data_grassi,year,value,`2000`:`2023`) %>% 
  mutate(gas="CO2 LULUCF (Inventory)") %>% 
  filter(country=="World") %>% 
  filter(category=="LULUCF net") %>% 
  mutate(value=value*1e6) %>%
  mutate(year=as.numeric(year)) %>% 
  filter(!is.na(year)) %>% 
  filter(year<=2021)

#data_grassi <- read.xlsx('sources/not public/Grassi_et_al_LULUCF.xlsx')
# data_grassi <- gather(data_grassi,year,value,-country,-iso) %>% 
#   mutate(gas="CO2 LULUCF (Inventory)") %>% 
#   filter(country=="World") %>% 
#   mutate(value=value*1e6) %>%
#   mutate(year=as.numeric(year)) %>% 
#   filter(!is.na(year)) %>% 
#   filter(year<=2021)

data_table <- rbind(data_ghg,data_grassi)
data_table <- data_table %>% 
  mutate(gas=ifelse(gas=="CO2 LULUCF","CO2 LULUCF (Bookkeeping)",gas))


# Select time frames for reporting (2010s, 2021, 2022, 2023)

data_table <- data_table %>% 
  group_by(year,gas) %>% 
  summarise(value=sum(value,na.rm=T)/1e9) %>% 
  mutate(cut=ifelse(year>=2010 & year <=2019,"2010-2019",NA)) %>% 
  mutate(cut=ifelse(year==2021,"2021",cut)) %>% 
  mutate(cut=ifelse(year==2022,"2022",cut)) %>% 
  mutate(cut=ifelse(year==2023,"2023",cut))


# Save a data frame for subsequent calculation of total GHG emissions

data_table_ghgs <- data_table


# Calculate total emissions by gas in each reporting year

data_table <- data_table %>% 
  filter(!is.na(cut)) %>% 
  group_by(gas,cut) %>% 
  summarise(value=mean(value))


# Calculate uncertainties for individual gases following the IPCC AR6 WG3 convention

uncertainties = data.frame(gas=c("CO2 Fossil","CO2 LULUCF (Bookkeeping)","CO2 LULUCF (Inventory)","CH4","N2O","F-gases"),uncertainty=c(0.08,0.7,0.7,0.3,0.6,0.3))

data_table <- left_join(data_table,uncertainties,by="gas")
data_table <- data_table %>% 
  mutate(uncertainty_abs=value*uncertainty) %>% 
  mutate(value=ifelse(gas=="CO2 Fossil",signif(value,3),signif(value,2))) %>% 
  mutate(uncertainty_abs=signif(uncertainty_abs,2))

data_table <- data_table %>% 
  mutate(value=paste0(value,"±",uncertainty_abs))


# Calculate total GHG emissions in the selected time frames, excluding inventory LULUCF

data_table_ghgs <- left_join(data_table_ghgs %>% filter(!is.na(cut)),uncertainties,by="gas")

data_table_ghgs <- data_table_ghgs %>% 
  filter(gas!="CO2 LULUCF (Inventory)") %>% 
  group_by(cut,gas,uncertainty) %>% 
  summarise(value=mean(value,na.rm=TRUE))

# Calculate uncertainty ranges for total GHG emissions, following IPCC AR6 WG3 convention

data_table_ghgs <- data_table_ghgs %>% 
  mutate(uncertainty_abs=value*uncertainty) %>% 
  mutate(uncertainty_abs=uncertainty_abs^2) %>% 
  filter(!is.na(cut)) %>% 
  group_by(cut) %>% 
  summarise(value=sum(value,na.rm=TRUE),
            uncertainty_abs=sqrt(sum(uncertainty_abs,na.rm=TRUE)))

data_table_ghgs <- data_table_ghgs %>% 
  mutate(gas="GHG") %>% 
  mutate(value=signif(value,3)) %>% 
  mutate(uncertainty_abs=signif(uncertainty_abs,2)) %>% 
  mutate(value=paste0(value,"±",uncertainty_abs))


# Join data by gas and GHG, tidy up variables

data_table <- rbind(data_table,data_table_ghgs)
data_table <- data_table %>% 
  select(-uncertainty,-uncertainty_abs)


# Arrange factor levels

data_table$gas <- as.factor(data_table$gas)
data_table$gas <- fct_relevel(data_table$gas,"GHG","CO2 Fossil","CO2 LULUCF (Bookkeeping)","CO2 LULUCF (Inventory)","CH4","N2O","F-gases")
data_table <- spread(data_table,cut,value)


# Save data to excel file

wb <- createWorkbook()
options("openxlsx.numFmt" = "0.00")
addWorksheet(wb,"table_1")
writeData(wb, sheet = "table_1", data_table, colNames = T, rowNames = F)


```
## Table of total emissions by year (for data file)

``` {r table_totals_long}

# Calculate total emissions by gas

data_table_totals <- data_ghg %>% 
  filter(year>=1990) %>% 
  group_by(gas,year) %>% 
  summarise(value=sum(value,na.rm=TRUE)/1e9)


# Calculate total GHG emissions

data_table_totals <- rbind(data_table_totals,data_table_totals %>% 
                             group_by(year) %>% 
                             summarise(value=sum(value,na.rm=TRUE)) %>% 
                             mutate(gas="GHG"))


# Compile and join national GHG inventory LULUCF data, for comparison with bookkeeping data

data_grassi <- read.xlsx('sources/not public/Grassi_et_al_LULUCF.xlsx')
data_grassi <- gather(data_grassi,year,value,-country,-iso) %>% 
  mutate(gas="CO2 LULUCF (Inventory)") %>% 
  filter(country=="World") %>% 
  mutate(value=value*1e6) %>%
  mutate(value=value/1e9) %>% 
  mutate(year=as.numeric(year)) %>% 
  filter(!is.na(year)) %>% 
  filter(year<=2021) %>% 
  select(-country,-iso)

data_table_totals <- rbind(data_table_totals,data_grassi)
data_table_totals <- data_table_totals %>% 
  mutate(gas=ifelse(gas=="CO2 LULUCF","CO2 LULUCF (Bookkeeping)",gas))


# Create a separate row for cement carbonation

# data_cc <- left_join(data_gcb_co2_cc,data_table_totals %>% select(year,gas,value_co2_foss=value),by=c("year","gas"))
# data_cc <- data_cc %>% 
#   mutate(value=value/1e9) %>% 
#   mutate(value=value_co2_foss-value) %>% 
#   filter(year>=1990) %>%
#   mutate(gas="CO2 Fossil (excl. cement carbonation)") %>% 
#   select(year,gas,value)
# 
# 
# data_table_totals <- rbind(data_table_totals,data_cc)


# Arrange factor levels

data_table_totals$gas <- as.factor(data_table_totals$gas)
data_table_totals$gas <- fct_relevel(data_table_totals$gas,"GHG","CO2 Fossil","CO2 LULUCF (Bookkeeping)","CH4","N2O","F-gases","CO2 LULUCF (Inventory)","CO2 Fossil (excl. cement carbonation)")


# Spread data and calculate relative and absolute changes in the latest year

data_table_totals <- spread(data_table_totals,year,value)
data_table_totals <- data_table_totals %>% 
  mutate(change_2022_2023_abs=`2023`-`2022`) %>% 
  mutate(change_2022_2023_rel=change_2022_2023_abs/`2022`)


# Add a blank row to separate values not in the total (inventory LULUCF and CO2 excl. carbonation)

data_table_totals <- rbind(data_table_totals %>% 
                             ungroup() %>% 
                             filter(!gas %in% c("CO2 LULUCF (Inventory)","CO2 Fossil (excl. cement carbonation)")) %>% 
                             add_row(),
                           data_table_totals %>% filter(gas %in% c("CO2 LULUCF (Inventory)","CO2 Fossil (excl. cement carbonation)")))


# Write to excel file

pct = createStyle(numFmt="0.0%")

addWorksheet(wb,"total_by_gas")
writeData(wb, sheet = "total_by_gas", data_table_totals, colNames = T, rowNames = F)

addStyle(wb, "total_by_gas",style=pct,
         cols=length(data_table_totals),
         rows=1:length(data_table_totals$gas)+1,
         gridExpand=TRUE)


```

## Table of total emissions by sector (for data file)

``` {r table_sectors}

# Calculate total emissions by sector

data_table_sectors <- data_ghg %>% 
  filter(year>=1990) %>%
  group_by(sector_lv1,sector_lv2,sector_lv3,year) %>%
  summarise(value=sum(value,na.rm=TRUE)/1e9)


# Spread and calculate relative and absolute emission changes in the latest year

data_table_sectors <- spread(data_table_sectors,year,value)
data_table_sectors <- data_table_sectors %>% 
  mutate(change_2022_2023_abs=`2023`-`2022`) %>% 
  mutate(change_2022_2023_rel=change_2022_2023_abs/`2022`)


# Write to excel file

addWorksheet(wb,"total_by_sector")
writeData(wb, sheet = "total_by_sector", data_table_sectors, colNames = T, rowNames = F)

addStyle(wb, "total_by_sector",style=pct,
         cols=length(data_table_sectors),
         rows=2:length(data_table_sectors$sector_lv1)+1,
         gridExpand=TRUE)

```

## Plot figure showing the share of global emissions in each sector

``` {r figure_global_sector_shares,fig.height=7,fig.width=9,fig.path="results/",dev=c('png','pdf','svg')}

# Calculate emissions by sector (first level) in 2023

plot_sector_shares_1 <- data_ghg %>% 
  filter(year==2023) %>% 
  group_by(sector_lv2,sector_lv2_colours,sector_lv2_icons) %>% 
  summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
  ungroup()


# Calculate the share of total for each sector at the first level

plot_sector_shares_1 <- plot_sector_shares_1 %>% 
  mutate(total=sum(plot_sector_shares_1$value)) %>% 
  mutate(share=value/total) %>% 
  mutate(share=round(share*100))


# Calculate the position of each label

plot_sector_shares_1 <- plot_sector_shares_1 %>% 
  arrange(desc(sector_lv2)) %>% 
  mutate(label_position=value) %>% 
  mutate(label_position=cumsum(label_position)) %>% 
  mutate(label_position=label_position-(value/2)) %>% 
  mutate(label=paste0(sector_lv2,"\n (",share,"%)"))
  

# Plot figure at the first level
  
p2 <- plot_sector_shares_1 %>% 
  ggplot(.,aes(x=1.6,y=value,fill=sector_lv2)) +
  
  geom_col(color="#636363",width=0.5) +
  geom_text(aes(x=1.3,y=label_position,label=label),size=3.5,hjust=1) + 
  geom_image(aes(x=1.6,y=label_position,image=sector_lv2_icons),by = "height",size=0.03) + 
  geom_text(data=plot_sector_shares_1 %>% filter(sector_lv2=="Energy: Power"),
            aes(x=1.6,y=59.5,label=paste0(signif(total,3)," GtCO2e in 2023"))) +
  
  xlim(0,3) +
  ylim(0,60) +
  scale_fill_manual(values = rev(plot_sector_shares_1$sector_lv2_colours)) +
  
  theme_wl() +
  theme(legend.position="none",
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0,0,0,0),"cm"))


# Calculate emissions by sector (second level) in 2023

plot_sector_shares_2 <- data_ghg %>% 
  filter(year==2023) %>% 
  group_by(sector_lv2,sector_lv2_colours,sector_lv3) %>% 
  summarise(value=sum(value,na.rm=TRUE)/1e9) %>% 
  ungroup() %>% 
  mutate()


# Calculate the share of total for each sector at the second level

plot_sector_shares_2 <- plot_sector_shares_2 %>% 
  mutate(total=sum(plot_sector_shares_2$value)) %>% 
  mutate(share=value/total) %>% 
  mutate(share=round(share*100))


# Calculate the position of each label

plot_sector_shares_2 <- plot_sector_shares_2 %>% 
  arrange(desc(sector_lv3)) %>% 
  mutate(label_position=value) %>% 
  mutate(label_position=cumsum(label_position)) %>% 
  mutate(label_position=label_position-(value/2)) %>% 
  mutate(label=paste0(sector_lv3," (",share,"%)"))
  

# Plot figure at the second level  

p3 <- plot_sector_shares_2 %>% 
  ggplot(.,aes(x=1,y=value,fill=sector_lv2)) +
  
  geom_col(color="#636363") +
  geom_text_repel(data=plot_sector_shares_2 %>% filter(!sector_lv2 %in% c("Energy: Power","Energy: Industry","Energy: Buildings")),
                  aes(x=1.6,y=label_position,label=label),
    nudge_x      = 0.25,
    direction    = "y",
    hjust        = 0,
    segment.size = 0.2,
    point.size = NA,
    size=3.5,
    ylim = c(-3,60)
  ) +
  
  xlim(0,8) +
  ylim(0,60) +
  scale_fill_manual(values = rev(plot_sector_shares_1$sector_lv2_colours)) +
  
  theme_wl() +
  theme(legend.position="none",
        axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        plot.background = element_blank(),
        plot.margin = unit(c(0,0,0,0),"cm"))


# Join figure

p2 + plot_spacer() + p3  + plot_layout(widths=c(2.2,-1.2,4)) + plot_annotation(title="Total greenhouse gas emissions by sector in 2023",
                                                                               subtitle=bquote("Gt" ~CO[2]~ "/year"),
                                                                               theme=theme(plot.title=element_text(hjust=0.25),
                                                                                           plot.subtitle = element_text(hjust=0.25)))

# Save figure data for designers

# data_table_sector_share <- rbind(plot_sector_shares_1 %>%
#                  arrange(sector_lv2) %>%
#                  mutate(column=1) %>%
#                  select(column,sector=sector_lv2,value,share,label),
#                plot_sector_shares_2 %>%
#                  arrange(sector_lv3) %>%
#                  mutate(column=2) %>%
#                  select(column,sector=sector_lv3,value,share,label))
# data_table_sector_share <- data_table_sector_share %>%
#   select(column,label,value,share)
# 
# 
# addWorksheet(wb,"shares_by_sector")
# writeData(wb, sheet = "shares_by_sector", data_table_sector_share, colNames = T, rowNames = F)


```

``` {r figure_changes_by_sector,fig.width=7,fig.height=4,fig.path="results/",dev=c('png','pdf')}

data_changes <- data_ghg %>% 
  filter(year %in% c(2022,2023)) %>% 
  group_by(year,sector_lv2,sector_lv2_colours) %>% 
  summarise(value=sum(value,na.rm=T)/1e9)

data_changes <- spread(data_changes,year,value)
data_changes <- data_changes %>% 
  mutate(change_abs=`2023`-`2022`,
         change_rel=change_abs/`2022`)

###

data_changes <- data_ghg %>%
  filter(year >= 1990 ) %>% 
  group_by(year,sector_lv2,sector_lv2_colours) %>% 
  summarise(value=sum(value,na.rm=T)/1e9) %>% 
  mutate(change_abs=NA)
sectors <- unique(data_changes$sector_lv2)

for (j in 1:length(sectors)) {
  
for (i in 1991:2023) {
  
  data_changes$change_abs[data_changes$year==i & data_changes$sector_lv2==sectors[j]] <- 
    data_changes$value[data_changes$year==i & data_changes$sector_lv2==sectors[j]] -
    data_changes$value[data_changes$year==i-1 & data_changes$sector_lv2==sectors[j]]
  
}
}

sector_colours <- data_changes %>% select(sector_lv2,sector_lv2_colours) %>% distinct()


data_changes %>% 
  filter(year>=2015) %>% 
  mutate(year=as.factor(year)) %>% 
  ggplot(.,aes(x=year,y=change_abs,fill=sector_lv2)) +
  geom_col(color="#636363") +
  geom_hline(yintercept=0) +
  geom_point(data=data_changes %>% filter(year>=2015) %>% mutate(year=as.factor(year)) %>%  group_by(year) %>% summarise(change_abs=sum(change_abs)),
             inherit.aes=FALSE,aes(x=year,y=change_abs)) +
  scale_fill_manual(values=sector_colours$sector_lv2_colours) +
  theme_wl() +
  labs(title="Change in total emissions by year and sector",
       subtitle="GtCO2e") +
  theme(axis.title = element_blank(),
        legend.title = element_blank())




```

``` {r save}

# Save excel file

saveWorkbook(wb,paste0("results/UNEP-Gap-Report-2024-Chapter-2-Data-Global.xlsx"),overwrite=T)

```