---
title: "UNEP-Gap-Report-2024-Compare-Versions"
author: "William F. Lamb"
date: "28 6 2024"
output: word_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

rm(list = ls())

library(tidyverse)
library(openxlsx)
library(countrycode)
library(ggrepel)
library(patchwork)
library(zoo)
library(RColorBrewer)
library(WDI)
library(labelled)
library(grid)
library(ggimage)

source("https://raw.githubusercontent.com/lambwf/Codebase/main/figure_style.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/reshape_with_labels.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/locate_shares.R")
source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_gcb_countries_v2023.R")


```

```{r load_EDGAR_v9}

source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_edgar_v9.R")


## load EDGAR data (https://edgar.jrc.ec.europa.eu/dataset_ghg80)

edgar_co2 <- read.xlsx("sources/not public/EDGAR_2024_CO2_1970_2023.xlsx",sheet=1,startRow=9)
edgar_ch4 <- read.xlsx("sources/not public/EDGAR_2024_CH4_1970_2023.xlsx",sheet=1,startRow = 9)
edgar_n2o <- read.xlsx("sources/not public/EDGAR_2024_N2O_1970_2023.xlsx",sheet=1,startRow = 9)
edgar_fgas <- read.xlsx("sources/not public/EDGAR_2024_F-gases_1970_2023.xlsx",sheet=1,startRow = 9)
data_ghg <- load_edgar(edgar_co2,edgar_ch4,edgar_n2o,edgar_fgas)


## join GWPs and calculate CO2e

gwps <- read.csv("https://raw.githubusercontent.com/openclimatedata/globalwarmingpotentials/main/globalwarmingpotentials.csv",skip = 10)

data_ghg$gas <- gsub("-","",data_ghg$gas)
data_ghg <- left_join(data_ghg,gwps %>% select(gas=Species,AR6GWP100)) %>% 
  mutate(AR6GWP100=ifelse(gas=="CO2",1,AR6GWP100))

## check all gwps joined

check <- data_ghg %>% filter(is.na(AR6GWP100))
check <- data_ghg %>% select(gas,AR6GWP100) %>% distinct()

data_ghg <- data_ghg %>% mutate(value_gwp=value*AR6GWP100)


list_fgases <- data_ghg %>% 
  select(gas) %>% 
  distinct() %>% 
  mutate(group=ifelse(gas=="CO2","CO2 Fossil",NA)) %>% 
  mutate(group=ifelse(gas=="CH4","CH4",group)) %>% 
  mutate(group=ifelse(gas=="N2O","N2O",group)) %>% 
  mutate(group=ifelse(is.na(group),"Fgases",group))

data_ghg <- left_join(data_ghg,list_fgases,by="gas")
data_ghg <- data_ghg %>% 
  mutate(gas=group) %>% 
  group_by(iso,country,code,code_description,gas,year) %>% 
  summarise(value=sum(value_gwp,na.rm=TRUE))

## Gg to tons

data_ghg$value = data_ghg$value*1000


## aggregate totals

data_ghg <- data_ghg %>% 
  group_by(iso,country,code,code_description,gas,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## aggregate sectors

write.xlsx(data_ghg %>% ungroup() %>% select(code,code_description) %>% distinct() %>% arrange(code),"cc_sectors.xlsx")
data_ghg <- left_join(data_ghg,read.xlsx("sources/cc_sectors.xlsx"),by=join_by(code, code_description))

data_ghg$gas <- as.factor(data_ghg$gas)
data_ghg$gas <- fct_relevel(data_ghg$gas,"CO2 Fossil","CO2 LULUCF","CH4","N2O","Fgases")

data_ghg$sector_lv1 <- as.factor(data_ghg$sector_lv1)
data_ghg$sector_lv1 <- fct_reorder(data_ghg$sector_lv1,data_ghg$sector_lv1_order)

data_ghg$sector_lv2 <- as.factor(data_ghg$sector_lv2)
data_ghg$sector_lv2 <- fct_reorder(data_ghg$sector_lv2,data_ghg$sector_lv2_order)

data_ghg$sector_lv2_alt <- as.factor(data_ghg$sector_lv2_alt)
data_ghg$sector_lv2_alt <- fct_reorder(data_ghg$sector_lv2_alt,data_ghg$sector_lv2_order)

data_ghg$sector_lv3 <- as.factor(data_ghg$sector_lv3)
data_ghg$sector_lv3 <- fct_reorder(data_ghg$sector_lv3,data_ghg$sector_lv3_order)


data_ghg_v9 <- data_ghg

```

```{r load_EDGAR_v8}


source("https://raw.githubusercontent.com/lambwf/Codebase/main/load_edgar_v8.R")


## load EDGAR data (https://edgar.jrc.ec.europa.eu/dataset_ghg80)

edgar_co2 <- read.xlsx("sources/IEA_EDGAR_CO2_1970_2022.xlsx",sheet=2,startRow=9)
edgar_ch4 <- read.xlsx("sources/EDGAR_CH4_1970_2022.xlsx",sheet=2,startRow = 9)
edgar_n2o <- read.xlsx("sources/EDGAR_N2O_1970_2022.xlsx",sheet=2,startRow = 9)
edgar_fgas <- read.xlsx("sources/EDGAR_F-gases_1990_2022.xlsx",sheet=2,startRow = 9)
data_ghg <- load_edgar(edgar_co2,edgar_ch4,edgar_n2o,edgar_fgas)


## join GWPs and calculate CO2e

gwps <- read.csv("https://raw.githubusercontent.com/openclimatedata/globalwarmingpotentials/main/globalwarmingpotentials.csv",skip = 10)

data_ghg$gas <- gsub("-","",data_ghg$gas)
data_ghg <- left_join(data_ghg,gwps %>% select(gas=Species,AR6GWP100)) %>% 
  mutate(AR6GWP100=ifelse(gas=="CO2",1,AR6GWP100))

## check all gwps joined

check <- data_ghg %>% filter(is.na(AR6GWP100))
check <- data_ghg %>% select(gas,AR6GWP100) %>% distinct()

data_ghg <- data_ghg %>% mutate(value_gwp=value*AR6GWP100)


list_fgases <- data_ghg %>% 
  select(gas) %>% 
  distinct() %>% 
  mutate(group=ifelse(gas=="CO2","CO2 Fossil",NA)) %>% 
  mutate(group=ifelse(gas=="CH4","CH4",group)) %>% 
  mutate(group=ifelse(gas=="N2O","N2O",group)) %>% 
  mutate(group=ifelse(is.na(group),"Fgases",group))

data_ghg <- left_join(data_ghg,list_fgases,by="gas")
data_ghg <- data_ghg %>% 
  mutate(gas=group) %>% 
  group_by(iso,country,code,code_description,gas,year) %>% 
  summarise(value=sum(value_gwp,na.rm=TRUE))

## Gg to tons

data_ghg$value = data_ghg$value*1000


## aggregate totals

data_ghg <- data_ghg %>% 
  group_by(iso,country,code,code_description,gas,year) %>% 
  summarise(value=sum(value,na.rm=TRUE))


## aggregate sectors

write.xlsx(data_ghg %>% ungroup() %>% select(code,code_description) %>% distinct() %>% arrange(code),"cc_sectors.xlsx")
data_ghg <- left_join(data_ghg,read.xlsx("sources/cc_sectors.xlsx"),by=join_by(code, code_description))

data_ghg$gas <- as.factor(data_ghg$gas)
data_ghg$gas <- fct_relevel(data_ghg$gas,"CO2 Fossil","CO2 LULUCF","CH4","N2O","Fgases")

data_ghg$sector_lv1 <- as.factor(data_ghg$sector_lv1)
data_ghg$sector_lv1 <- fct_reorder(data_ghg$sector_lv1,data_ghg$sector_lv1_order)

data_ghg$sector_lv2 <- as.factor(data_ghg$sector_lv2)
data_ghg$sector_lv2 <- fct_reorder(data_ghg$sector_lv2,data_ghg$sector_lv2_order)

data_ghg$sector_lv2_alt <- as.factor(data_ghg$sector_lv2_alt)
data_ghg$sector_lv2_alt <- fct_reorder(data_ghg$sector_lv2_alt,data_ghg$sector_lv2_order)

data_ghg$sector_lv3 <- as.factor(data_ghg$sector_lv3)
data_ghg$sector_lv3 <- fct_reorder(data_ghg$sector_lv3,data_ghg$sector_lv3_order)

data_ghg_v8 <- data_ghg
```


```{r compare}


data_compare <- rbind(data_ghg_v8 %>% mutate(version="EDGARv8"),
                      data_ghg_v9 %>% mutate(version="EDGARv9"))

blarg <- data_compare %>% 
  group_by(year,gas,version) %>% 
  summarise(value=sum(value,na.rm=T)/1e9)
blarg <- spread(blarg,version,value)
blarg <- blarg %>% 
  mutate(difference=EDGARv9-EDGARv8)

data_compare %>% 
  group_by(year,gas,version) %>% 
  summarise(value=sum(value,na.rm=T)/1e9) %>% 
  ggplot(.,aes(x=year,y=value,color=version)) +
  geom_path() +
  theme_wl() +
  facet_wrap(.~gas,scales="free_y")



data_compare %>% 
  filter(gas=="CH4") %>% 
  group_by(year,sector_lv3,version) %>% 
  summarise(value=sum(value,na.rm=T)/1e9) %>%
  ggplot(.,aes(x=year,y=value,color=version)) +
  geom_path() +
  theme_wl() +
  facet_wrap(.~sector_lv3,scales="free_y")



data_compare %>% 
  group_by(year,country,iso,version) %>% 
  summarise(value=sum(value,na.rm=T)/1e9) %>% 
  filter(iso %in% c("USA","CHN","IND","RUS","SAU")) %>% 
  ggplot(.,aes(x=year,y=value,color=version)) +
  geom_path() +
  theme_wl() +
  facet_wrap(.~country,scales="free_y")


```
